/**
 * Phase 7G — Audit Intelligence.
 *
 * This module reads the append-only ledger that every other control depends on, so the suite must
 * prove four things above all:
 *
 *   1. It NEVER writes to audit_log or enterprise_events. An audit reader that can modify the
 *      ledger it inspects destroys the property that makes the ledger worth having.
 *   2. It never declares an anomaly. POTENTIAL_ANOMALY paired with human review is the ceiling.
 *   3. An empty window is reported as empty WITH its bounds — silence is never assurance.
 *   4. Event classification is enforced against clearance, and an unrecognised clearance grants
 *      nothing (the Phase 7F escalation, re-tested on more sensitive data).
 *
 * NON-VACUITY. audit_log and enterprise_events are EMPTY at seed, so positive controls must first
 * generate real activity through the real platform and assert on it. Every positive control below
 * asserts a specific non-zero count.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { sql } from "drizzle-orm";
import { db } from "@/db";
import { ROLES, ROLE_CLEARANCE } from "@/lib/constants";
import type { Principal } from "@/lib/authz";
import { runSpecialist, type SpecialistContext } from "@/lib/specialist/platform";
import {
  AUDIT_INTEL_VERSION,
  actorActivity,
  activityTimeline,
  assertWindow,
  auditDataQuality,
  compareSequence,
  correlate,
  failedActionAnalysis,
  governanceActivity,
  inspectEvidenceChain,
  privilegedActionAnalysis,
  unsupportedAnalyses,
} from "@/lib/specialist/audit/engines";
import {
  analyzeActorActivity,
  analyzeFailedActions,
  analyzeGovernanceActivity,
  analyzePrivilegedActions,
  correlateEvents,
  generateAuditReport,
  inspectChain,
  readActivityTimeline,
  reportUnsupportedAnalyses,
  searchAuditRecords,
} from "@/lib/specialist/audit/service";
import type { AuditRecordView, AuditWindow, EventRecordView } from "@/lib/specialist/audit/model";

const RUN = `AI${Date.now()}`;
let n = 0;
const trace = () => `${RUN}-${String(++n).padStart(3, "0")}`;

let tenantId = "";
let foreignTenantId = "";
let foreignEntityId = "";
/** Records generated by this suite, so positive controls assert on known real activity. */
let generatedTraceIds: string[] = [];

const WINDOW: AuditWindow = { from: "2020-01-01", to: "2030-12-31" };

async function rowsOf<T>(q: Parameters<typeof db.execute>[0]): Promise<T[]> {
  const r = (await db.execute(q)) as unknown as { rows?: T[] };
  return r.rows ?? (r as unknown as T[]);
}
async function count(q: Parameters<typeof db.execute>[0]): Promise<number> {
  return Number((await rowsOf<{ n: number }>(q))[0].n);
}

function principal(overrides: Partial<Principal> = {}): Principal {
  const roles = overrides.roles ?? ["AUDITOR"];
  const permissions = new Set<never>();
  for (const role of roles) {
    const def = (ROLES as Record<string, { permissions?: readonly string[] }>)[role];
    for (const p of def?.permissions ?? []) permissions.add(p as never);
  }
  const rank = (c: string) =>
    ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED", "HIGHLY_RESTRICTED"].indexOf(c);
  let clearance = "PUBLIC";
  for (const role of roles) {
    const c = (ROLE_CLEARANCE as Record<string, string>)[role] ?? "INTERNAL";
    if (rank(c) > rank(clearance)) clearance = c;
  }
  return {
    userId: "USR_AUDIT_TEST",
    partyId: "p",
    email: "audit@example.test",
    displayName: "Audit Test",
    tenantId,
    tenantCode: "BEYU",
    tenantType: "ENTERPRISE",
    roles,
    permissions,
    clearance,
    entityScope: [],
    mfaSatisfied: true,
    sessionId: "s",
    riskScore: 0,
    emergencyPermissions: [],
    ...overrides,
  } as unknown as Principal;
}

function ctx(overrides: Partial<SpecialistContext> = {}): SpecialistContext {
  return { principal: principal(), tenantId, legalEntityId: null, traceId: trace(), ...overrides };
}

/** SYNTHETIC engine fixtures. */
const rec = (over: Partial<AuditRecordView> = {}): AuditRecordView => ({
  id: "AUD_SYN",
  sequence: "100",
  tenantId: "TEN_SYN",
  actorUserId: "USR_SYN",
  actorType: "HUMAN",
  action: "specialist.test.run",
  objectType: "SPECIALIST_RESULT",
  objectId: "OBJ_SYN",
  outcome: "SUCCESS",
  reason: null,
  authority: null,
  traceId: "TRACE_SYN",
  occurredAt: "2026-01-15T10:00:00.000Z",
  hash: "hash-a",
  prevHash: null,
  basis: "OBSERVED",
  ...over,
});

const evt = (over: Partial<EventRecordView> = {}): EventRecordView => ({
  id: "EVT_SYN",
  sequence: "200",
  type: "SPECIALIST_ANALYSIS_PRODUCED",
  source: "specialist.test",
  tenantId: "TEN_SYN",
  subjectType: "SPECIALIST_RESULT",
  subjectId: "OBJ_SYN",
  actorUserId: "USR_SYN",
  actorType: "HUMAN",
  classification: "INTERNAL",
  traceId: "TRACE_SYN",
  occurredAt: "2026-01-15T10:00:00.000Z",
  hash: "hash-b",
  prevHash: null,
  basis: "OBSERVED",
  ...over,
});

beforeAll(async () => {
  const [t] = await rowsOf<{ id: string }>(sql`select id from tenants where id = 'TEN_BEYU_GROUP'`);
  tenantId = t.id;

  const [f] = await rowsOf<{ id: string; tenant_id: string }>(
    sql`select id, tenant_id from legal_entities where tenant_id <> ${tenantId} order by id limit 1`,
  );
  foreignEntityId = f.id;
  foreignTenantId = f.tenant_id;

  // NON-VACUITY: the ledgers are empty at seed, so generate REAL activity through the REAL
  // platform. Positive controls below assert on these specific records.
  const gen = principal({ roles: ["GROUP_CFO"], userId: "USR_GENERATOR" });
  generatedTraceIds = [];
  for (let i = 0; i < 3; i += 1) {
    const tid = `${RUN}-GEN-${i}`;
    generatedTraceIds.push(tid);
    await runSpecialist(
      {
        specialist: "TREASURY",
        operation: "ANALYZE_CASH",
        kind: "ANALYSIS",
        permission: "finance:treasury.read",
        version: "test-1.0.0",
        riskClass: "MEDIUM",
      },
      { principal: gen, tenantId, legalEntityId: null, traceId: tid },
      async () => ({
        data: {},
        provenance: { sources: [{ type: "TREASURY_POSITION", id: "TRS_T1" }], assumptions: [], blockedBy: [] },
        explanation: ["generated for audit-intelligence positive controls"],
      }),
    );
  }

  // Prove the fixture is real before any positive control depends on it.
  expect(await count(sql`select count(*)::int as n from audit_log where tenant_id = ${tenantId}`))
    .toBeGreaterThanOrEqual(3);
  expect(await count(sql`select count(*)::int as n from enterprise_events where tenant_id = ${tenantId}`))
    .toBeGreaterThanOrEqual(3);
  expect(foreignTenantId).not.toBe(tenantId);
});

// ===========================================================================
// A. NO FABRICATED CERTAINTY
// ===========================================================================

describe("audit engines — absence is never assurance", () => {
  it("returns DATA_NOT_AVAILABLE, not 'no activity', for an empty record set", () => {
    const r = actorActivity([]);
    expect(r.basis).toBe("DATA_NOT_AVAILABLE");
    expect(r.actors).toEqual([]);
    expect(r.explanation.join(" ")).toMatch(/not evidence that no activity occurred/i);
  });

  it("returns DATA_NOT_AVAILABLE for an empty timeline and empty failure analysis", () => {
    expect(activityTimeline([]).basis).toBe("DATA_NOT_AVAILABLE");
    expect(failedActionAnalysis([]).basis).toBe("DATA_NOT_AVAILABLE");
    expect(governanceActivity([]).basis).toBe("DATA_NOT_AVAILABLE");
  });

  it("never reports a single-record chain as verified", () => {
    const r = inspectEvidenceChain([{ sequence: "1", hash: "h", prevHash: null }]);
    expect(r.linkageVerified).toBeNull();
    expect(r.basis).toBe("DATA_NOT_AVAILABLE");
    expect(r.explanation.join(" ")).toMatch(/would overstate the check/i);
  });

  it("never reports an empty chain as verified", () => {
    const r = inspectEvidenceChain([]);
    expect(r.linkageVerified).toBeNull();
    expect(r.recordsInspected).toBe(0);
  });

  it("states the limits of what chain verification proves", () => {
    const r = inspectEvidenceChain([
      { sequence: "1", hash: "a", prevHash: null },
      { sequence: "2", hash: "b", prevHash: "a" },
    ]);
    expect(r.linkageVerified).toBe(true);
    expect(r.verificationScope).toMatch(/does NOT recompute cryptographic digests/i);
    expect(r.verificationScope).toMatch(/does NOT prove the chain was never rewritten/i);
  });
});

// ===========================================================================
// B. NOTHING IS AN ANOMALY
// ===========================================================================

describe("audit engines — no anomaly is ever declared", () => {
  it("reports denials as OBSERVED facts, not accusations", () => {
    const r = failedActionAnalysis([rec({ id: "A", outcome: "DENIED" })]);
    expect(r.observations[0].code).toBe("DENIED_ACTION");
    expect(r.observations[0].basis).toBe("OBSERVED");
    expect(r.explanation.join(" ")).toMatch(/not by itself evidence of an attack/i);
  });

  it("flags repetition ONLY against a caller-supplied threshold", () => {
    const denials = [1, 2, 3].map((i) => rec({ id: `A${i}`, outcome: "DENIED" }));
    const noThreshold = failedActionAnalysis(denials);
    expect(noThreshold.observations.filter((o) => o.code === "REPEATED_DENIAL")).toHaveLength(0);
    expect(noThreshold.explanation.join(" ")).toMatch(/no ratified threshold to default to/i);

    const withThreshold = failedActionAnalysis(denials, { repeatedDenialThreshold: 3 });
    const flagged = withThreshold.observations.find((o) => o.code === "REPEATED_DENIAL")!;
    expect(flagged.basis).toBe("POTENTIAL_ANOMALY");
    expect(flagged.detail).toMatch(/not a finding of misconduct/i);
  });

  it("rejects a nonsensical repetition threshold", () => {
    expect(() => failedActionAnalysis([rec()], { repeatedDenialThreshold: 0 })).toThrow(/positive integer/i);
    expect(() => failedActionAnalysis([rec()], { repeatedDenialThreshold: 1.5 })).toThrow(/positive integer/i);
  });

  it("never emits a verdict stronger than POTENTIAL_ANOMALY", () => {
    const all = [
      ...failedActionAnalysis([rec({ outcome: "DENIED" })], { repeatedDenialThreshold: 1 }).observations,
      ...auditDataQuality([rec({ occurredAt: "2030-01-01T00:00:00.000Z" })], [], { asOf: "2026-02-15" }).observations,
    ];
    expect(all.length).toBeGreaterThan(0);
    for (const o of all) {
      expect(["OBSERVED", "POTENTIAL_ANOMALY", "REQUIRES_HUMAN_REVIEW"]).toContain(o.basis);
      expect(o.advisoryOnly).toBe(true);
    }
  });

  it("does not infer privilege from action names", () => {
    const dangerous = [
      rec({ id: "A", action: "finance.ledger.delete" }),
      rec({ id: "B", action: "admin.superuser.grant" }),
    ];
    const r = privilegedActionAnalysis(dangerous, []);
    expect(r.basis).toBe("DATA_NOT_AVAILABLE");
    expect(r.records).toEqual([]);
    expect(r.explanation.join(" ")).toMatch(/will not infer it from action names/i);
  });

  it("counts privileged actions only from the caller's declared list", () => {
    const r = privilegedActionAnalysis(
      [rec({ id: "A", action: "governance.decision.approve" }), rec({ id: "B", action: "read.something" })],
      ["governance.decision.approve"],
    );
    expect(r.records.map((x) => x.id)).toEqual(["A"]);
    expect(r.explanation.join(" ")).toMatch(/expected activity, not a finding/i);
  });

  it("performs no statistical baseline analysis", () => {
    const unsupported = unsupportedAnalyses();
    const baseline = unsupported.find((u) => u.analysis === "BEHAVIOURAL_BASELINE")!;
    expect(baseline.basis).toBe("DATA_NOT_AVAILABLE");
    expect(baseline.explanation.join(" ")).toMatch(/manufacture accusations/i);
  });

  it("refuses authentication analysis because no auth history exists", () => {
    const auth = unsupportedAnalyses().find((u) => u.analysis === "AUTHENTICATION_EVENTS")!;
    expect(auth.basis).toBe("DATA_NOT_AVAILABLE");
    expect(auth.explanation.join(" ")).toMatch(/would measure live sessions, not authentication behaviour/i);
  });

  it("refuses retention analysis because no retention policy is represented", () => {
    const ret = unsupportedAnalyses().find((u) => u.analysis === "RETENTION_COMPLIANCE")!;
    expect(ret.missingInputs.join(" ")).toMatch(/no retention period/i);
  });
});

// ===========================================================================
// C. CORRELATION AND CHAIN
// ===========================================================================

describe("audit engines — correlation and evidence chain", () => {
  it("correlates an audit record with its event by trace id", () => {
    const r = correlate([rec()], [evt()]);
    expect(r.correlations).toHaveLength(1);
    expect(r.correlations[0].complete).toBe(true);
    expect(r.correlations[0].auditRecordIds).toEqual(["AUD_SYN"]);
    expect(r.correlations[0].eventIds).toEqual(["EVT_SYN"]);
  });

  it("reports an orphaned event without inventing an audit record", () => {
    const r = correlate([], [evt()]);
    expect(r.correlations[0].complete).toBe(false);
    expect(r.correlations[0].auditRecordIds).toEqual([]);
    expect(r.observations.map((o) => o.code)).toContain("ORPHANED_EVENT");
    expect(r.explanation.join(" ")).toMatch(/No counterpart record is ever synthesised/i);
  });

  it("reports an orphaned audit record without inventing an event", () => {
    const r = correlate([rec()], []);
    expect(r.correlations[0].complete).toBe(false);
    expect(r.observations.map((o) => o.code)).toContain("ORPHANED_AUDIT_RECORD");
  });

  it("flags a record with no trace id as uncorrelatable", () => {
    const r = correlate([rec({ traceId: null })], []);
    expect(r.observations.map((o) => o.code)).toContain("MISSING_TRACE_ID");
  });

  it("detects a hash-chain discontinuity", () => {
    const r = inspectEvidenceChain([
      { sequence: "1", hash: "a", prevHash: null },
      { sequence: "2", hash: "b", prevHash: "WRONG" },
    ]);
    expect(r.linkageVerified).toBe(false);
    expect(r.discontinuities).toHaveLength(1);
    expect(r.discontinuities[0].atSequence).toBe("2");
    expect(r.discontinuities[0].detail).toMatch(/may indicate a gap in the queried scope rather than tampering/i);
  });

  it("orders by sequence exactly, beyond Number precision", () => {
    // Sequences past 2^53 must still order correctly.
    expect(compareSequence("9007199254740993", "9007199254740992")).toBeGreaterThan(0);
    expect(compareSequence("100", "99")).toBeGreaterThan(0);
    expect(compareSequence("5", "5")).toBe(0);
    const r = activityTimeline([rec({ id: "B", sequence: "1000" }), rec({ id: "A", sequence: "999" })]);
    expect(r.entries.map((e) => e.sequence)).toEqual(["999", "1000"]);
    expect(r.explanation.join(" ")).toMatch(/clock adjustment cannot reorder history/i);
  });
});

// ===========================================================================
// D. DATA QUALITY (§12)
// ===========================================================================

describe("audit engines — data quality surfaced, never repaired", () => {
  it("detects missing actor and tenant identity", () => {
    const r = auditDataQuality([rec({ actorUserId: null, tenantId: null })], [], { asOf: "2026-02-15" });
    expect(r.observations.map((o) => o.code)).toEqual(
      expect.arrayContaining(["MISSING_ACTOR_IDENTITY", "MISSING_TENANT_IDENTITY"]),
    );
  });

  it("detects a duplicate record id", () => {
    const r = auditDataQuality([rec({ id: "DUP" }), rec({ id: "DUP", sequence: "101" })], [], { asOf: "2026-02-15" });
    expect(r.observations.map((o) => o.code)).toContain("DUPLICATE_RECORD_ID");
  });

  it("detects future-dated records in both ledgers", () => {
    const r = auditDataQuality(
      [rec({ occurredAt: "2030-01-01T00:00:00.000Z" })],
      [evt({ occurredAt: "2030-01-01T00:00:00.000Z" })],
      { asOf: "2026-02-15" },
    );
    expect(r.observations.filter((o) => o.code === "FUTURE_DATED_RECORD")).toHaveLength(2);
  });

  it("detects a sequence regression", () => {
    const r = auditDataQuality([rec({ id: "A", sequence: "200" }), rec({ id: "B", sequence: "100" })], [], { asOf: "2026-02-15" });
    expect(r.observations.map((o) => o.code)).toContain("OUT_OF_ORDER_SEQUENCE");
  });

  it("states that findings are never repaired", () => {
    const r = auditDataQuality([rec({ actorUserId: null })], [], { asOf: "2026-02-15" });
    expect(r.explanation.join(" ")).toMatch(/never repaired/i);
  });

  it("rejects a malformed asOf", () => {
    expect(() => auditDataQuality([rec()], [], { asOf: "15/02/2026" })).toThrow(/ISO date/i);
  });
});

// ===========================================================================
// E. TEMPORAL (§6)
// ===========================================================================

describe("audit engines — window validation", () => {
  it("accepts a valid window", () => {
    expect(() => assertWindow({ from: "2026-01-01", to: "2026-12-31" })).not.toThrow();
  });
  it("accepts a single-day window", () => {
    expect(() => assertWindow({ from: "2026-01-01", to: "2026-01-01" })).not.toThrow();
  });
  it("rejects an inverted window", () => {
    expect(() => assertWindow({ from: "2026-12-31", to: "2026-01-01" })).toThrow(/must not be after/i);
  });
  it("rejects malformed bounds", () => {
    expect(() => assertWindow({ from: "01/01/2026", to: "2026-12-31" })).toThrow(/ISO date/i);
    expect(() => assertWindow({ from: "2026-01-01", to: "not-a-date" })).toThrow(/ISO date/i);
  });
});

// ===========================================================================
// F. POSITIVE CONTROLS ON REAL GENERATED ACTIVITY (§9)
// ===========================================================================

describe("audit service — positive controls on real ledger activity", () => {
  it("searches and finds the real records this suite generated", async () => {
    const r = await searchAuditRecords(ctx(), { window: WINDOW });
    expect(r.version).toBe(AUDIT_INTEL_VERSION);
    expect(r.data.records.length).toBeGreaterThanOrEqual(3);
    const found = r.data.records.filter((x) => generatedTraceIds.includes(x.objectId));
    expect(found).toHaveLength(3);
    expect(found.every((x) => x.action === "specialist.treasury.analyze_cash")).toBe(true);
    expect(found.every((x) => x.outcome === "SUCCESS")).toBe(true);
  });

  it("filters by actor, action and outcome against real data", async () => {
    const byActor = await searchAuditRecords(ctx(), { window: WINDOW, actorUserId: "USR_GENERATOR" });
    expect(byActor.data.records.length).toBeGreaterThanOrEqual(3);
    expect(byActor.data.records.every((x) => x.actorUserId === "USR_GENERATOR")).toBe(true);

    const byOutcome = await searchAuditRecords(ctx(), {
      window: WINDOW,
      outcome: "DENIED",
      actorUserId: "USR_GENERATOR",
    });
    // This suite generated no denials for USR_GENERATOR. Other suites (HTTP 403,
    // TOTP replay) may append DENIED rows to the same tenant ledger; a global
    // empty-DENIED assertion is therefore not an invariant of this module.
    expect(byOutcome.data.records).toHaveLength(0);
    expect(byOutcome.explanation.join(" ")).toMatch(/not evidence that the activity never occurred/i);
  });

  it("Phase 7G FIX: real records carry a trace id and the authorising permission", async () => {
    const r = await searchAuditRecords(ctx(), { window: WINDOW, actorUserId: "USR_GENERATOR" });
    const record = r.data.records.find((x) => x.objectId === generatedTraceIds[0])!;
    // Before this phase both were absent: trace_id was NULL and permission was never recorded.
    expect(record.traceId).toBe(generatedTraceIds[0]);

    const [row] = await rowsOf<{ perm: string }>(
      sql`select new_value->>'permission' as perm from audit_log where object_id = ${generatedTraceIds[0]}`,
    );
    expect(row.perm).toBe("finance:treasury.read");
  });

  it("correlates real audit records with their real events", async () => {
    const r = await correlateEvents(ctx(), { window: WINDOW });
    const mine = r.data.correlations.filter((c) => generatedTraceIds.includes(c.traceId));
    expect(mine).toHaveLength(3);
    expect(mine.every((c) => c.complete)).toBe(true);
    expect(mine.every((c) => c.auditRecordIds.length === 1 && c.eventIds.length === 1)).toBe(true);
  });

  it("analyses real actor activity", async () => {
    const r = await analyzeActorActivity(ctx(), { window: WINDOW });
    const generator = r.data.actors.find((a) => a.actorUserId === "USR_GENERATOR")!;
    expect(generator).toBeDefined();
    expect(generator.totalActions).toBeGreaterThanOrEqual(3);
    expect(generator.successCount).toBeGreaterThanOrEqual(3);
    expect(generator.distinctActions).toContain("specialist.treasury.analyze_cash");
  });

  it("returns a real timeline ordered by sequence", async () => {
    const r = await readActivityTimeline(ctx(), { window: WINDOW });
    expect(r.data.entries.length).toBeGreaterThanOrEqual(3);
    const seqs = r.data.entries.map((e) => e.sequence);
    const sorted = [...seqs].sort(compareSequence);
    expect(seqs).toEqual(sorted);
  });

  it("inspects the real chain and reports linkage honestly", async () => {
    const r = await inspectChain(ctx(), { window: WINDOW });
    expect(r.data.recordsInspected).toBeGreaterThanOrEqual(3);
    expect(r.data.verificationScope).toMatch(/does NOT recompute/i);
    expect(r.explanation.join(" ")).toMatch(/gaps are expected/i);
  });

  it("generates a real report with observations and explicit refusals", async () => {
    const r = await generateAuditReport(ctx(), { window: WINDOW });
    expect(r.data.auditRecordCount).toBeGreaterThanOrEqual(3);
    expect(r.data.eventCount).toBeGreaterThanOrEqual(3);
    expect(r.data.actorCount).toBeGreaterThanOrEqual(1);
    expect(r.data.outcomeCounts.SUCCESS).toBeGreaterThanOrEqual(3);
    expect(r.data.topActions.length).toBeGreaterThan(0);
    expect(r.data.unsupported).toHaveLength(3);
    expect(r.explanation.join(" ")).toMatch(/freezes nothing, revokes nothing and remediates nothing/i);
  });

  it("reports an empty window as empty, with its bounds", async () => {
    const r = await generateAuditReport(ctx(), { window: { from: "2019-01-01", to: "2019-01-02" } });
    expect(r.data.auditRecordCount).toBe(0);
    expect(r.data.basis).toBe("DATA_NOT_AVAILABLE");
    const empty = r.data.observations.find((o) => o.code === "EMPTY_WINDOW")!;
    expect(empty.detail).toContain("2019-01-01");
    expect(empty.detail).toMatch(/not assurance that nothing happened/i);
  });

  it("analyses governance activity over real records", async () => {
    const r = await analyzeGovernanceActivity(ctx(), { window: WINDOW });
    // The generated records are SPECIALIST_RESULT, not governance objects: correctly zero.
    expect(r.data.basis).toBe("OBSERVED");
    expect(r.data.records.every((x) => x.objectType !== "SPECIALIST_RESULT")).toBe(true);
    expect(r.data.explanation.join(" ")).toMatch(/not inference from action names/i);
  });

  it("reports unsupported analyses through the service", async () => {
    const r = await reportUnsupportedAnalyses(ctx());
    expect(r.data.unsupported.map((u) => u.analysis).sort()).toEqual([
      "AUTHENTICATION_EVENTS", "BEHAVIOURAL_BASELINE", "RETENTION_COMPLIANCE",
    ]);
  });

  it("is deterministic across repeated runs", async () => {
    const a = await analyzeActorActivity(ctx(), { window: WINDOW });
    const b = await analyzeActorActivity(ctx(), { window: WINDOW });
    // Actor totals grow as this suite audits itself, so compare the stable shape rather than counts.
    expect(a.data.actors.map((x) => x.actorUserId).sort()).toEqual(b.data.actors.map((x) => x.actorUserId).sort());
  });
});

// ===========================================================================
// G. TENANT ISOLATION
// ===========================================================================

describe("audit service — tenant isolation", () => {
  it("refuses a tenant the principal does not belong to", async () => {
    await expect(searchAuditRecords({ principal: principal(), tenantId: foreignTenantId, legalEntityId: null, traceId: trace() }))
      .rejects.toMatchObject({ code: "NOT_FOUND" });
  });

  it("refuses a forged tenant id", async () => {
    await expect(searchAuditRecords({ principal: principal(), tenantId: "TEN_FORGED", legalEntityId: null, traceId: trace() }))
      .rejects.toMatchObject({ code: "NOT_FOUND" });
  });

  it("CRITICAL: returns no records of another tenant to that tenant's own principal", async () => {
    const r = await searchAuditRecords({
      principal: principal({ tenantId: foreignTenantId }),
      tenantId: foreignTenantId, legalEntityId: null, traceId: trace(),
    }, { window: WINDOW });
    // All generated activity belongs to TEN_BEYU_GROUP.
    expect(r.data.records.every((x) => x.tenantId === foreignTenantId)).toBe(true);
    expect(r.data.records.filter((x) => generatedTraceIds.includes(x.objectId))).toHaveLength(0);
  });

  it("cannot retrieve another tenant's record by enumerating its object id", async () => {
    const target = generatedTraceIds[0];
    const r = await searchAuditRecords({
      principal: principal({ tenantId: foreignTenantId }),
      tenantId: foreignTenantId, legalEntityId: null, traceId: trace(),
    }, { window: WINDOW });
    expect(JSON.stringify(r.data.records)).not.toContain(target);
  });

  it("cannot correlate using another tenant's trace id", async () => {
    const r = await correlateEvents({
      principal: principal({ tenantId: foreignTenantId }),
      tenantId: foreignTenantId, legalEntityId: null, traceId: trace(),
    }, { window: WINDOW });
    expect(r.data.correlations.filter((c) => generatedTraceIds.includes(c.traceId))).toHaveLength(0);
  });
});

// ===========================================================================
// H. ENTITY ISOLATION
// ===========================================================================

describe("audit service — entity isolation", () => {
  it("refuses an entity owned by another tenant", async () => {
    await expect(searchAuditRecords({ principal: principal(), tenantId, legalEntityId: foreignEntityId, traceId: trace() }))
      .rejects.toMatchObject({ code: "NOT_FOUND" });
  });

  it("refuses an entity outside the principal's entity scope", async () => {
    const [owned] = await rowsOf<{ id: string }>(
      sql`select id from legal_entities where tenant_id = ${tenantId} order by id limit 1`,
    );
    await expect(searchAuditRecords({
      principal: principal({ entityScope: ["LEN_SOMETHING_ELSE"] }),
      tenantId, legalEntityId: owned.id, traceId: trace(),
    })).rejects.toMatchObject({ code: "NOT_FOUND" });
  });

  it("POSITIVE: an in-scope entity is accepted and echoed on the result", async () => {
    const [owned] = await rowsOf<{ id: string }>(
      sql`select id from legal_entities where tenant_id = ${tenantId} order by id limit 1`,
    );
    const r = await searchAuditRecords({
      principal: principal({ entityScope: [owned.id] }),
      tenantId, legalEntityId: owned.id, traceId: trace(),
    }, { window: WINDOW });
    expect(r.legalEntityId).toBe(owned.id);
    expect(r.data.records.length).toBeGreaterThanOrEqual(3);
  });
});

// ===========================================================================
// I. RBAC AND CLEARANCE (§5)
// ===========================================================================

describe("audit service — permission and clearance", () => {
  it("denies a principal without audit:log.read", async () => {
    // HCM_DIRECTOR has no audit permission at all.
    const hcm = principal({ roles: ["HCM_DIRECTOR"] });
    expect(hcm.permissions.has("audit:log.read" as never)).toBe(false);
    await expect(searchAuditRecords(ctx({ principal: hcm }))).rejects.toMatchObject({ code: "DENIED" });
  });

  it("denies a principal with no roles", async () => {
    await expect(searchAuditRecords(ctx({ principal: principal({ roles: [] }) })))
      .rejects.toMatchObject({ code: "DENIED" });
  });

  it("POSITIVE: AUDITOR holds audit:log.read and succeeds", async () => {
    const r = await searchAuditRecords(ctx({ principal: principal({ roles: ["AUDITOR"] }) }), { window: WINDOW });
    expect(r.data.records.length).toBeGreaterThanOrEqual(3);
  });

  it("CRITICAL: correlation requires audit:event.read, not just audit:log.read", async () => {
    // CHIEF_RISK_COMPLIANCE holds audit:log.read but NOT audit:event.read.
    const crc = principal({ roles: ["CHIEF_RISK_COMPLIANCE"] });
    expect(crc.permissions.has("audit:log.read" as never)).toBe(true);
    expect(crc.permissions.has("audit:event.read" as never)).toBe(false);
    await expect(correlateEvents(ctx({ principal: crc }), { window: WINDOW }))
      .rejects.toThrow(/audit:event.read/i);
  });

  it("the full report also requires audit:event.read", async () => {
    const crc = principal({ roles: ["CHIEF_RISK_COMPLIANCE"] });
    await expect(generateAuditReport(ctx({ principal: crc }), { window: WINDOW }))
      .rejects.toThrow(/audit:event.read/i);
  });

  it("CRITICAL: an unrecognised clearance grants NO event visibility (fails closed)", async () => {
    const forged = principal({ roles: ["AUDITOR"], clearance: "SUPER_ADMIN" as never });
    const r = await correlateEvents(ctx({ principal: forged }), { window: WINDOW });
    // Every event is withheld; no correlation can be completed from event data.
    expect(r.data.withheldEventCount).toBeGreaterThan(0);
    expect(r.data.correlations.every((c) => c.eventIds.length === 0)).toBe(true);
  });

  it("POSITIVE: a recognised clearance sees events and reports zero withheld", async () => {
    const r = await correlateEvents(ctx({ principal: principal({ roles: ["AUDITOR"] }) }), { window: WINDOW });
    expect(r.data.withheldEventCount).toBe(0);
    expect(r.data.correlations.some((c) => c.eventIds.length > 0)).toBe(true);
  });

  it("states that a clearance-limited result is PARTIAL", async () => {
    const forged = principal({ roles: ["AUDITOR"], clearance: "NONSENSE" as never });
    const r = await correlateEvents(ctx({ principal: forged }), { window: WINDOW });
    expect(r.explanation.join(" ")).toMatch(/PARTIAL/);
  });
});

// ===========================================================================
// J. ATTACK MATRIX (§10)
// ===========================================================================

describe("audit service — hostile inputs", () => {
  it("rejects malformed trace ids", async () => {
    for (const traceId of ["", "short", "has space", "x".repeat(65)]) {
      await expect(searchAuditRecords(ctx({ traceId }))).rejects.toMatchObject({ code: "RULE_VIOLATION" });
    }
  });

  it("rejects a malformed or inverted window rather than defaulting", async () => {
    await expect(searchAuditRecords(ctx(), { window: { from: "01/01/2026", to: "2026-12-31" } }))
      .rejects.toThrow(/ISO date/i);
    await expect(searchAuditRecords(ctx(), { window: { from: "2026-12-31", to: "2026-01-01" } }))
      .rejects.toThrow(/must not be after/i);
  });

  it("rejects a nonsensical limit", async () => {
    await expect(searchAuditRecords(ctx(), { window: WINDOW, limit: 0 })).rejects.toThrow(/positive integer/i);
    await expect(searchAuditRecords(ctx(), { window: WINDOW, limit: -5 })).rejects.toThrow(/positive integer/i);
  });

  it("does not expose sensitive audit payload fields", async () => {
    const r = await searchAuditRecords(ctx(), { window: WINDOW });
    const record = r.data.records[0] as unknown as Record<string, unknown>;
    // ip_address, user_agent, old_value and new_value are deliberately not surfaced.
    expect(record).not.toHaveProperty("ipAddress");
    expect(record).not.toHaveProperty("userAgent");
    expect(record).not.toHaveProperty("oldValue");
    expect(record).not.toHaveProperty("newValue");
  });

  it("does not activate or alter any capability", async () => {
    const before = await rowsOf(sql`select capability_code, activation_status from governance_capability_registry order by capability_code`);
    await generateAuditReport(ctx(), { window: WINDOW });
    expect(await rowsOf(sql`select capability_code, activation_status from governance_capability_registry order by capability_code`)).toEqual(before);
  });

  it("registers audit capabilities with every enforcement path LOCKED", async () => {
    const rows = await rowsOf<{ capability_code: string; activation_status: string; required_decisions: string[] }>(
      sql`select capability_code, activation_status, required_decisions from governance_capability_registry
          where capability_code like 'CAP_SPEC_AUDIT%' order by capability_code`,
    );
    expect(rows.every((r) => r.activation_status === "LOCKED")).toBe(true);
    for (const code of ["CAP_SPEC_AUDIT_REMEDIATE", "CAP_SPEC_AUDIT_FREEZE", "CAP_SPEC_AUDIT_ENFORCE"]) {
      const cap = rows.find((r) => r.capability_code === code)!;
      expect(cap).toBeDefined();
      expect(cap.required_decisions.length).toBeGreaterThan(0);
    }
    expect(rows.find((r) => r.capability_code === "CAP_SPEC_AUDIT_ENFORCE")!.required_decisions).toContain("P1");
  });

  it("creates no enforcement permission", async () => {
    expect(await count(sql`
      select count(*)::int as n from role_permissions
      where permission_code in ('audit:enforce','audit:freeze','audit:remediate','finance:ledger.approve')
    `)).toBe(0);
  });

  it("creates no journal entries and funds no capital", async () => {
    await generateAuditReport(ctx(), { window: WINDOW });
    expect(await count(sql`select count(*)::int as n from journal_entries`)).toBe(0);
    expect(await count(sql`select count(*)::int as n from capital_requests where status = 'FUNDED'`)).toBe(0);
  });
});

// ===========================================================================
// K. THE LEDGER IS NEVER MUTATED (§10.20, §11)
// ===========================================================================

describe("audit module — never mutates the ledger it inspects", () => {
  /**
   * The audit ledger GROWS as this module runs, because every ANALYSIS is itself audited. So a
   * naive count comparison is useless here. What must hold is that EXISTING rows are never
   * modified or removed — verified by xmin (catches even an idempotent UPDATE, the Phase 7F/7E
   * lesson) over a fixed set of pre-existing ids.
   */
  it("never modifies or deletes an existing audit record (xmin stable)", async () => {
    const before = await rowsOf<{ id: string; v: string }>(
      sql`select id, xmin::text as v from audit_log where object_id = ${generatedTraceIds[0]}`,
    );
    expect(before.length).toBeGreaterThan(0);

    await generateAuditReport(ctx(), { window: WINDOW });
    await analyzeFailedActions(ctx(), { window: WINDOW });
    await analyzePrivilegedActions(ctx(), ["specialist.treasury.analyze_cash"], { window: WINDOW });
    await inspectChain(ctx(), { window: WINDOW });

    const after = await rowsOf<{ id: string; v: string }>(
      sql`select id, xmin::text as v from audit_log where object_id = ${generatedTraceIds[0]}`,
    );
    expect(after).toEqual(before);
  });

  it("never modifies an existing enterprise event (xmin stable)", async () => {
    const before = await rowsOf<{ id: string; v: string }>(
      sql`select id, xmin::text as v from enterprise_events where subject_id = ${generatedTraceIds[0]}`,
    );
    expect(before.length).toBeGreaterThan(0);
    await correlateEvents(ctx(), { window: WINDOW });
    expect(await rowsOf<{ id: string; v: string }>(
      sql`select id, xmin::text as v from enterprise_events where subject_id = ${generatedTraceIds[0]}`,
    )).toEqual(before);
  });

  it("the immutability triggers remain armed", async () => {
    const rows = await rowsOf<{ tgname: string; tgenabled: string }>(sql`
      select t.tgname, t.tgenabled from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      where not t.tgisinternal and c.relname in ('audit_log','enterprise_events')
      order by t.tgname
    `);
    expect(rows).toHaveLength(4);
    expect(rows.every((r) => r.tgenabled === "O")).toBe(true);
  });

  it("defines no tables of its own", async () => {
    const names = (await rowsOf<{ table_name: string }>(sql`
      select table_name from information_schema.tables
      where table_schema = 'public' and (table_name like '%audit%' or table_name like '%event%')
      order by table_name
    `)).map((r) => r.table_name);
    // The ledger-domain tables: baseline + internal_event_receipts (Phase 8
    // governed cross-OS event idempotency — part of the ledger domain, RLS-
    // isolated like audit_log). Nothing else added.
    expect(names).toEqual([
      "audit_chain_heads",
      "audit_log",
      "employment_events",
      "enterprise_events",
      "internal_event_receipts",
    ]);
  });

  it("adds no migration", async () => {
    // 25 = migrations 0000-0019 (prior baseline) + 0020_service_principals
    // + 0021_financial_ledger_rls + 0022_chart_of_accounts_tenant_uniqueness
    // + 0023_noelia_ai_platform
    // + 0024_noelia_model_runtime
    // (Phase 8 events, Phase 6 service-principal registry, ledger RLS,
    // chart-of-accounts tenant hardening and Phase 1 Noelia AI platform:
    // all additive/hardening).
    expect(await count(sql`select count(*)::int as n from public.beyu_migrations`)).toBe(25);
  });

  it("leaves the decision registry entirely PENDING", async () => {
    expect(await count(sql`select count(*)::int as n from governance_decision_registry where status <> 'PENDING'`)).toBe(0);
  });
});

afterAll(async () => {
  // The ledgers legitimately grew (this module audits itself). What must remain true is that the
  // immutability controls are still armed and no decision was activated.
  const disabled = await count(sql`select count(*)::int as n from pg_trigger where tgenabled = 'D' and not tgisinternal`);
  expect(disabled).toBe(0);
});
