/** BEYU OS platform constants — single definition, consumed everywhere. */

export const SYSTEM_VERSION = "BEYU-OS/1.0.0";
export const ENGINE_VERSION_WATERFALL = "waterfall-engine/1.2.0";
export const NOELIA_IDENTITY = "NOELIA";
export const HIVE_RUNTIME = "HIVE";
/** Governed scheduler/worker service identity — distinct from the interactive Noelia identity. */
export const NOELIA_SCHEDULER_IDENTITY = "NOELIA_SCHEDULER";
export const NOELIA_PROMPT_VERSION = "noelia-prompt/2.0.0";
export const SESSION_COOKIE = "beyu_os_session";
/** httpOnly cookie carrying the one-time administrator enrollment token. */
export const BOOTSTRAP_ENROLLMENT_COOKIE = "beyu_os_admin_enrollment";
export const SESSION_TTL_HOURS = 12;

/**
 * Canonical strategic horizons (Noelia executive intelligence metadata).
 *
 * Horizons are INTELLIGENCE METADATA, never automatic authority levels. A
 * longer horizon implies no additional authority; every recommendation remains
 * subject to the full BEYU governance boundary regardless of horizon.
 */
export const NOELIA_HORIZONS = [
  "HORIZON_1_IMMEDIATE",
  "HORIZON_2_NEAR_TERM",
  "HORIZON_3_MEDIUM_TERM",
  "HORIZON_4_LONG_TERM",
  "HORIZON_5_GENERATIONAL",
  "HORIZON_6_INSTITUTIONAL_CONTINUITY_100Y",
] as const;
export type NoeliaHorizon = (typeof NOELIA_HORIZONS)[number];

export const HORIZON_LABELS: Record<NoeliaHorizon, string> = {
  HORIZON_1_IMMEDIATE: "Immediate (0–90 days)",
  HORIZON_2_NEAR_TERM: "Near term (90 days–1 year)",
  HORIZON_3_MEDIUM_TERM: "Medium term (1–3 years)",
  HORIZON_4_LONG_TERM: "Long term (3–10 years)",
  HORIZON_5_GENERATIONAL: "Generational (10–30 years)",
  HORIZON_6_INSTITUTIONAL_CONTINUITY_100Y: "Institutional continuity (30–100 years)",
};

/**
 * Canonical analytic epistemics for every Noelia analytical result.
 *
 * Every finding, metric and recommendation must carry one of these statuses.
 * The mapping to the legacy ai_output_class enum is lossless: these statuses
 * are the fine-grained classes, and the outputClass remains the coarse
 * envelope for the ai_decisions table.
 */
export const NOELIA_EPISTEMIC_STATUS = [
  "OBSERVED",
  "DERIVED",
  "FORECAST",
  "SCENARIO",
  "INFERENCE",
  "RECOMMENDATION",
  "PREDICTION",
  "UNCERTAINTY",
  "UNAVAILABLE",
  "UNVERIFIED",
  "STALE",
  "REQUIRES_HUMAN_REVIEW",
] as const;
export type NoeliaEpistemicStatus = (typeof NOELIA_EPISTEMIC_STATUS)[number];

export const EPISTEMIC_STATUS_LABELS: Record<NoeliaEpistemicStatus, string> = {
  OBSERVED: "Directly measured from an authoritative source.",
  DERIVED: "Computed deterministically from OBSERVED inputs.",
  FORECAST: "A projection from observed history. Never a fact.",
  SCENARIO: "A hypothetical world. Never financial truth.",
  INFERENCE: "A reasoned conclusion from evidence; not directly measured.",
  RECOMMENDATION: "A proposed course of action; requires accountable decision.",
  PREDICTION: "A statement about an unobserved future state.",
  UNCERTAINTY: "Evidence is insufficient or conflicting.",
  UNAVAILABLE: "The data does not exist or is not in scope. Never zero.",
  UNVERIFIED: "Retrieved but not verified as authoritative.",
  STALE: "Outside its governed validity window.",
  REQUIRES_HUMAN_REVIEW: "A human with authority must decide.",
};

export const CLASSIFICATION_ORDER = [
  "PUBLIC",
  "INTERNAL",
  "CONFIDENTIAL",
  "RESTRICTED",
  "HIGHLY_RESTRICTED",
] as const;

export type Classification = (typeof CLASSIFICATION_ORDER)[number];

export function classificationRank(c: string): number {
  const idx = CLASSIFICATION_ORDER.indexOf(c as Classification);
  return idx < 0 ? CLASSIFICATION_ORDER.length : idx;
}

/** Known catalogue only. Unknown strings must never be treated as a clearance. */
export function isKnownClassification(c: string): c is Classification {
  return (CLASSIFICATION_ORDER as readonly string[]).includes(c);
}

/**
 * Canonical permission catalogue (domain:object.action).
 * A capability that is not listed here does not exist constitutionally.
 */
export const PERMISSIONS = {
  // Control plane
  "platform:dashboard.read": "View the executive control centre",
  "platform:config.manage": "Manage configuration and feature flags",
  "platform:registry.read": "Read the OS / source-of-truth registry",
  "platform:registry.manage": "Register or retire an OS",
  // Identity
  "identity:user.read": "Read identity records",
  "identity:user.manage": "Create, suspend or revoke identities",
  "identity:role.grant": "Grant or revoke role assignments",
  "identity:emergency.activate": "Activate break-glass emergency access",
  // Organization & ownership
  "organization:entity.read": "Read corporate structure",
  "organization:entity.manage": "Create or amend legal entities",
  "organization:ownership.read": "Read ownership and beneficial ownership",
  "organization:ownership.manage": "Record ownership changes",
  // Governance
  "governance:body.read": "Read governance bodies",
  "governance:resolution.read": "Read resolutions",
  "governance:resolution.propose": "Propose a resolution",
  "governance:resolution.vote": "Cast a governance vote",
  "governance:resolution.approve": "Record a resolution outcome",
  "governance:policy.read": "Read policies",
  "governance:policy.manage": "Author or amend policy",
  // Risk / compliance / legal
  "risk:register.read": "Read the enterprise risk register",
  "risk:register.manage": "Create or update risks and controls",
  "compliance:obligation.read": "Read compliance obligations",
  "compliance:assessment.manage": "Record compliance assessments",
  "legal:matter.read": "Read legal matters",
  "legal:matter.manage": "Manage legal matters",
  // Finance
  "finance:ledger.read": "Read financial records",
  "finance:ledger.post": "Post journal entries",
  "finance:treasury.read": "Read treasury positions",
  "finance:capital.read": "Read capital requests",
  "finance:capital.manage": "Create or amend capital requests",
  "finance:waterfall.read": "Read waterfall configurations and runs",
  "finance:waterfall.simulate": "Simulate a waterfall distribution",
  "finance:waterfall.commit": "Commit a waterfall run (requires resolution)",
  "finance:tax.read": "Read tax strategy intelligence",
  "finance:tax.assess": "Assess tax strategy eligibility",
  // Payments & banking integration. Deliberately split read / ingest / review /
  // authorize / configure: a single "payments" permission would let one grant
  // carry both ingestion and payout authorisation, which is the separation of
  // duties this domain exists to enforce.
  "finance:payments.read": "Read payment transactions, settlements and exceptions",
  "finance:payments.ingest": "Ingest provider events and settlement batches (no ledger effect)",
  "finance:payments.review": "Confirm or reject a proposed payment match; resolve an exception",
  "finance:payments.authorize": "Authorize a payment transaction for accounting and accept residual risk",
  "finance:payments.configure": "Propose payment configuration; the database write itself requires the admin DSN",
  "finance:settlement.manage": "Manage settlement batches and clearing reconciliation",
  // Workforce
  "hcm:employee.read": "Read workforce records",
  "hcm:employee.manage": "Manage workforce records",
  // Family office
  "family:member.read": "Read the family registry",
  "family:member.manage": "Manage family lineage records",
  "family:beneficiary.read": "Read beneficiary entitlements",
  "family:beneficiary.manage": "Manage beneficiary entitlements",
  "family:vault.read": "Read family vault index",
  // Family office — capital & wealth domain.
  //
  // These EXTEND the five permissions above; they do not replace them. The
  // split is read vs manage, and every `manage` is a governed mutation that
  // still requires a human actor, a recorded authority reference and an audit
  // append. None of these permissions can approve, transfer money, execute an
  // investment, change ownership or bypass CAP_POSTING (§24): those remain
  // `governance:resolution.approve`, `finance:payments.authorize`,
  // `finance:ledger.post` and `organization:ownership.manage` respectively, so
  // granting the whole Family Office capital set confers no money-moving
  // authority whatsoever.
  "familyoffice:capital.read": "Read the Family Office capital position, allocation cases and doctrine adoption",
  "familyoffice:capital.manage": "Record Family Office capital allocation cases and ladder positions",
  "familyoffice:investment.read": "Read Family Office investments, theses, valuations and portfolio aggregation",
  "familyoffice:investment.manage": "Record Family Office investments, theses and valuation marks",
  "familyoffice:obligation.read": "Read the obligation register (who owes whom), covenants and covenant tests",
  "familyoffice:obligation.manage": "Record and transition obligations and covenants",
  "familyoffice:realestate.read": "Read Family Office real-estate assets and financing models",
  "familyoffice:realestate.manage": "Record Family Office real-estate assets and financing models",
  "familyoffice:treasury.read": "Read Family Office treasury and liquidity projections",
  "familyoffice:cashflow.read": "Read consolidated Family Office cash flow and balance-sheet snapshots",
  "familyoffice:risk.read": "Read Family Office debt, risk and stress results",
  "familyoffice:liquidity.read": "Read Family Office liquidity positions and alerts",
  "familyoffice:scenario.read": "Read Family Office scenario models, results and capital simulations",
  "familyoffice:scenario.simulate": "Run a Family Office scenario or capital simulation (never executes anything)",
  "familyoffice:capitalrequest.read": "Read Family Office capital allocation cases against Finance OS capital requests",
  "familyoffice:capitalrequest.manage": "Raise and progress Family Office capital allocation cases",
  "familyoffice:committee.read": "Read investment committee decisions, quorum, votes and dissent",
  "familyoffice:committee.decide": "Record an investment committee decision (human only; requires authority reference)",
  "familyoffice:decisionjournal.read": "Read the investment decision journal and post-investment reviews",
  "familyoffice:decisionjournal.manage": "Record decision journal entries and post-investment reviews",
  "familyoffice:intelligence.read": "Read regulatory, market and tax intelligence",
  "familyoffice:intelligence.manage": "Record regulatory, market and tax intelligence items",
  "familyoffice:generational.read": "Read generational wealth plans, succession objectives and interests",
  "familyoffice:generational.manage": "Record generational plans and succession objectives",
  "familyoffice:education.read": "Read the family education curriculum and progress",
  "familyoffice:education.manage": "Publish family education lessons and record progress",
  "familyoffice:capital.postmortem": "Record a post-investment review outcome attribution",
  // Family office — PROTECTION & INSURANCE (life insurance as a governed Family
  // Office capability: §4–§26 of the protection design). Read is one gate
  // because the domain's sensitivity is uniform; the three write permissions
  // are deliberately split: recording a policy, changing an insurance
  // beneficiary designation, and progressing a claim are different acts with
  // different consequences. None of them posts money — Finance OS stays the
  // sole accounting authority and CAP_POSTING is never referenced here.
  "familyoffice:protection.read": "Read Family Office insurance policies, coverage, premiums, assignments, loans, reviews and protection assessments",
  "familyoffice:protection.manage": "Record and transition Family Office insurance policies, premium obligations, reviews and modeled protection assessments (never a posting)",
  "familyoffice:beneficiary.manage": "Record, supersede or revoke insurance beneficiary designations (distinct from trust beneficiary entitlements; consequential legal act — MFA step-up)",
  "familyoffice:claim.read": "Read the insurance claims ledger and proceeds posture (contingent vs received)",
  "familyoffice:claim.manage": "Record insurance claims and their lifecycle transitions (records the insurer's reported decision and the receipt; adjudication and money movement belong elsewhere)",
  // Documents / audit / AI
  "documents:registry.read": "Read the document & attachment registry",
  "documents:registry.manage": "Register or supersede documents",
  // Agriculture OS — sector operational records. SECTOR_OPERATOR is the
  // registry owner (read + manage). Named enterprise roles receive read only
  // by explicit grant (A-06-1); they never inherit via Object.keys(PERMISSIONS).
  "agriculture:data.read": "Read Agriculture OS operational records (farms, fields, crop cycles, harvests, livestock, land, aqua, inventory, work, observations, traceability)",
  "agriculture:data.manage": "Create or amend Agriculture OS operational records",
  // Foundation OS — ONE institutional OS; these are domain capabilities inside
  // it, not sub-OS products. Approval permissions are HIGH_RISK (MFA step-up).
  "foundation:registry.read": "Read the Foundation Registry",
  "foundation:registry.manage": "Register foundations and transition lifecycle states",
  "foundation:formation.read": "Read foundation formation cases",
  "foundation:formation.manage": "Run formation cases and record assessments",
  "foundation:structure.read": "Read organization structures and scenarios",
  "foundation:structure.manage": "Author structure proposals",
  "foundation:structure.simulate": "Run structure-change simulations",
  "foundation:governance.read": "Read foundation meetings and conflict declarations",
  "foundation:governance.manage": "Schedule meetings and record conflicts",
  "foundation:tax.read": "Read foundation tax profiles, rules and assessments",
  "foundation:tax.assess": "Record foundation tax assessments",
  "foundation:compliance.read": "Read foundation obligations, deadlines and tasks",
  "foundation:compliance.manage": "Manage obligations, deadlines, tasks, evidence and escalations",
  "foundation:donor.read": "Read donor profiles and donations",
  "foundation:donor.manage": "Manage donors, donations and pledges",
  "foundation:fund.read": "Read funds, restrictions and allocations",
  "foundation:fund.manage": "Manage funds, restrictions and allocations",
  "foundation:grant.read": "Read grantees, grants, milestones and disbursements",
  "foundation:grant.manage": "Manage grants across the grant lifecycle",
  "foundation:grant.approve": "Approve grants and disbursements (material decision)",
  "foundation:program.read": "Read foundation programs, projects and beneficiaries",
  "foundation:program.manage": "Manage programs, projects and beneficiary services",
  "foundation:beneficiary.read": "Read beneficiary records (restricted)",
  "foundation:beneficiary.manage": "Manage beneficiary eligibility, consent and services",
  "foundation:procurement.read": "Read suppliers and procurements",
  "foundation:procurement.manage": "Manage suppliers and the procurement lifecycle",
  "foundation:asset.read": "Read the foundation asset register",
  "foundation:asset.manage": "Manage assets across acquire → dispose",
  "foundation:investment.read": "Read investment policies and positions",
  "foundation:investment.manage": "Manage investment policies and proposals",
  "foundation:investment.approve": "Approve material investments (material decision)",
  "foundation:safeguarding.read": "Read safeguarding cases (highly restricted)",
  "foundation:safeguarding.manage": "Manage safeguarding cases and corrective action",
  "foundation:impact.read": "Read impact metrics and measurements",
  "foundation:impact.manage": "Manage impact metrics and record measurements",
  "foundation:assignment.read": "Read foundation workforce assignments",
  "foundation:assignment.manage": "Assign HCM workers to foundation contexts",
  // Government Integration Fabric — ONE shared gateway inside BEYU OS (not a
  // Government OS). Read/submit are deliberately split so holding registry
  // visibility never implies the authority to transmit data to a government
  // system. Submission is HIGH_RISK (MFA step-up): a fiscal receipt, claim or
  // report sent to a government authority is a material external act.
  "government:integration.read": "Read the government integration registry and submission records",
  "government:submission.manage": "Submit governed operations (fiscal, claims, reports, verifications) to government systems through the canonical gateway",
  "audit:log.read": "Read the immutable audit ledger",
  "audit:event.read": "Read the enterprise event stream",
  "ai:noelia.query": "Query Noelia AI",
  "ai:decision.review": "Review and dispose AI decisions",
  "ai:executive.read": "Request executive intelligence briefings",
  "ai:analytics.read": "Request governed enterprise analytics",
  "ai:workflow.run": "Run governed Noelia agentic workflows",
  "ai:workflow.approve": "Approve a Noelia workflow or prepared action",
  "ai:memory.read": "Read governed enterprise memory",
  "ai:memory.write": "Write governed enterprise memory",
  "ai:knowledge.ingest": "Register a governed knowledge source",
  "ai:schedule.manage": "Manage governed Noelia schedules",
  "ai:model.registry.read": "Read the governed model registry",
  "ai:model.registry.manage": "Register, approve, suspend or retire a governed model",
  "ai:model.router.read": "Read the governed model-router selection decision",
  "ai:provider.registry.read": "Read the governed AI provider registry",
  "ai:provider.registry.manage": "Register, assess, activate or suspend an AI provider",
  "ai:identity.read": "Read canonical AI identities",
  "ai:identity.manage": "Manage canonical AI identity state (suspend/retire)",
  "ai:evaluation.read": "Read governed AI model evaluation records",
  "ai:evaluation.manage": "Record or update governed AI model evaluation evidence",
  "ai:risk.register.read": "Read the BEYU AI risk register",
  "ai:risk.register.manage": "Maintain the BEYU AI risk register",
  "ai:incident.manage": "Manage AI incident containment/resolution records",
  "ai:killswitch.manage": "Activate or deactivate a Noelia kill switch",
  "ai:compliance.read": "Read AI requirements, applicability, controls, evidence and assurance records",
  "ai:compliance.write": "Create/update AI requirements, applicability, controls, evidence and assurance records",
  "ai:compliance.audit": "Run and manage AI internal audits, findings and corrective actions",
  "ai:compliance.certification": "Transition certification/readiness state using documented evidence",
  "ai:compliance.metrics": "Read AI compliance metrics, blocking controls and assurance dashboards",
} as const;

export type PermissionCode = keyof typeof PERMISSIONS;

/** Canonical Agriculture OS tenant code (seed `T.agri`). Agriculture writes require this tenant. */
export const AGRICULTURE_OS_TENANT_CODE = "BEYU-AGRI";

export const HIGH_RISK_PERMISSIONS: PermissionCode[] = [
  "identity:emergency.activate",
  "identity:role.grant",
  "organization:ownership.manage",
  "finance:ledger.post",
  "finance:payments.authorize",
  "finance:settlement.manage",
  "finance:waterfall.commit",
  "family:beneficiary.manage",
  // Changing an insurance beneficiary designation changes who receives a
  // contingent death benefit. It is a consequential legal act on the same
  // footing as a trust beneficiary change, so it carries the same MFA step-up.
  "familyoffice:beneficiary.manage",
  // Recording an investment committee decision is the moment capital authority
  // is created, so it carries the same MFA step-up as a resolution approval.
  "familyoffice:committee.decide",
  "governance:policy.manage",
  "government:submission.manage",
];

/** Canonical role catalogue with constitutional scope. */
export const ROLES: Record<
  string,
  { name: string; description: string; scope: string; privileged: boolean; permissions: PermissionCode[] }
> = {
  PLATFORM_ADMIN: {
    name: "Platform Administrator",
    description: "System administration of the BEYU OS control plane. No financial or governance authority.",
    scope: "ENTERPRISE",
    privileged: true,
    permissions: [
      "platform:dashboard.read",
      "platform:config.manage",
      "platform:registry.read",
      "platform:registry.manage",
      "identity:user.read",
      "identity:user.manage",
      "identity:role.grant",
      "audit:log.read",
      "audit:event.read",
      "documents:registry.read",
      "organization:entity.read",
      "ai:executive.read",
      "ai:analytics.read",
      "ai:memory.read",
      "ai:schedule.manage",
      "ai:model.registry.read",
      "ai:model.router.read",
      "ai:provider.registry.read",
      "ai:identity.read",
      "ai:evaluation.read",
      "ai:risk.register.read",
      "ai:compliance.read",
      "ai:compliance.write",
      "ai:compliance.audit",
      "ai:compliance.certification",
      "ai:compliance.metrics",
    ],
  },
  GROUP_CEO: {
    name: "Group Chief Executive",
    description: "Enterprise executive authority across all sectors, subject to board reserved matters.",
    scope: "ENTERPRISE",
    privileged: true,
    // Explicit enumeration (Finding A-06-1): previously computed via
    // Object.keys(PERMISSIONS).filter(exclusions), which silently granted the
    // CEO every permission added in the future. The effective set is unchanged;
    // new permissions now require an explicit decision to grant.
    permissions: [
      "platform:dashboard.read",
      "platform:registry.read",
      "platform:registry.manage",
      "identity:user.read",
      "identity:user.manage",
      "identity:role.grant",
      "organization:entity.read",
      "organization:entity.manage",
      "organization:ownership.read",
      "organization:ownership.manage",
      "governance:body.read",
      "governance:resolution.read",
      "governance:resolution.propose",
      "governance:resolution.vote",
      "governance:resolution.approve",
      "governance:policy.read",
      "governance:policy.manage",
      "risk:register.read",
      "risk:register.manage",
      "compliance:obligation.read",
      "compliance:assessment.manage",
      "legal:matter.read",
      "legal:matter.manage",
      "finance:ledger.read",
      "finance:treasury.read",
      "finance:capital.read",
      "finance:capital.manage",
      "finance:waterfall.read",
      "finance:waterfall.simulate",
      "finance:waterfall.commit",
      "finance:tax.read",
      "finance:tax.assess",
      "hcm:employee.read",
      "hcm:employee.manage",
      "family:member.read",
      "family:member.manage",
      "family:beneficiary.read",
      "family:beneficiary.manage",
      "family:vault.read",
      "documents:registry.read",
      "documents:registry.manage",
      "foundation:registry.read",
      "foundation:formation.read",
      "foundation:structure.read",
      "foundation:governance.read",
      "foundation:tax.read",
      "foundation:compliance.read",
      "foundation:donor.read",
      "foundation:fund.read",
      "foundation:grant.read",
      "foundation:grant.approve",
      "foundation:program.read",
      "foundation:beneficiary.read",
      "foundation:procurement.read",
      "foundation:asset.read",
      "foundation:investment.read",
      "foundation:investment.approve",
      "foundation:safeguarding.read",
      "foundation:impact.read",
      "foundation:assignment.read",
      "audit:log.read",
      "audit:event.read",
      "ai:noelia.query",
      "ai:decision.review",
      "ai:executive.read",
      "ai:analytics.read",
      "ai:workflow.run",
      "ai:workflow.approve",
      "ai:memory.read",
      "ai:memory.write",
      "ai:knowledge.ingest",
      "ai:schedule.manage",
      "ai:model.registry.read",
      "ai:model.router.read",
      "ai:provider.registry.read",
      "ai:identity.read",
      "ai:evaluation.read",
      "ai:risk.register.read",
      "ai:compliance.read",
      "ai:compliance.write",
      "ai:compliance.audit",
      "ai:compliance.certification",
      "ai:compliance.metrics",
      "agriculture:data.read",
    ] as PermissionCode[],
  },
  GROUP_CFO: {
    name: "Group Chief Financial Officer",
    description: "Authoritative for financial consequences, treasury, capital and tax governance.",
    scope: "ENTERPRISE",
    privileged: true,
    permissions: [
      "platform:dashboard.read",
      "organization:entity.read",
      "organization:ownership.read",
      "governance:resolution.read",
      "governance:resolution.propose",
      "governance:resolution.vote",
      "governance:policy.read",
      "risk:register.read",
      "compliance:obligation.read",
      "finance:ledger.read",
      "finance:ledger.post",
      "finance:payments.read",
      "finance:payments.ingest",
      "finance:payments.review",
      "finance:payments.authorize",
      "finance:payments.configure",
      "finance:settlement.manage",
      "finance:treasury.read",
      "finance:capital.read",
      "finance:capital.manage",
      "finance:waterfall.read",
      "finance:waterfall.simulate",
      "finance:waterfall.commit",
      "finance:tax.read",
      "finance:tax.assess",
      // Fiscal/statutory government submissions (TRA VFD, contributions) are a
      // CFO accountability; HIGH_RISK so MFA step-up applies.
      "government:integration.read",
      "government:submission.manage",
      "documents:registry.read",
      "audit:log.read",
      "ai:noelia.query",
      "ai:executive.read",
      "ai:analytics.read",
      "ai:memory.read",
      "ai:memory.write",
      "ai:workflow.run",
      "ai:model.registry.read",
      "agriculture:data.read",
    ],
  },
  CHIEF_GOVERNANCE_OFFICER: {
    name: "Chief Governance Officer",
    description: "Custodian of the Constitution, policy hierarchy and governance execution.",
    scope: "ENTERPRISE",
    privileged: true,
    permissions: [
      "platform:dashboard.read",
      "platform:registry.read",
      "organization:entity.read",
      "organization:ownership.read",
      "governance:body.read",
      "governance:resolution.read",
      "governance:resolution.propose",
      "governance:resolution.vote",
      "governance:resolution.approve",
      "governance:policy.read",
      "governance:policy.manage",
      "risk:register.read",
      "compliance:obligation.read",
      "compliance:assessment.manage",
      "legal:matter.read",
      "foundation:registry.read",
      "foundation:structure.read",
      "foundation:governance.read",
      "foundation:governance.manage",
      "foundation:compliance.read",
      "foundation:safeguarding.read",
      "documents:registry.read",
      "documents:registry.manage",
      "audit:log.read",
      "audit:event.read",
      "ai:noelia.query",
      "ai:decision.review",
      "ai:executive.read",
      "ai:analytics.read",
      "ai:workflow.approve",
      "ai:memory.read",
      "ai:memory.write",
      "ai:knowledge.ingest",
      "ai:schedule.manage",
      "ai:model.registry.read",
      "ai:model.router.read",
      "ai:provider.registry.read",
      "ai:identity.read",
      "ai:evaluation.read",
      "ai:risk.register.read",
      "ai:compliance.read",
      "ai:compliance.write",
      "ai:compliance.audit",
      "ai:compliance.certification",
      "ai:compliance.metrics",
    ],
  },
  CHIEF_RISK_COMPLIANCE: {
    name: "Chief Risk & Compliance Officer",
    description: "Enterprise risk register, controls, compliance assessment and regulatory obligations.",
    scope: "ENTERPRISE",
    privileged: false,
    permissions: [
      "platform:dashboard.read",
      "organization:entity.read",
      "governance:resolution.read",
      "governance:resolution.vote",
      "governance:policy.read",
      "risk:register.read",
      "risk:register.manage",
      "compliance:obligation.read",
      "compliance:assessment.manage",
      "legal:matter.read",
      "documents:registry.read",
      "audit:log.read",
      "ai:noelia.query",
      "ai:executive.read",
      "ai:analytics.read",
      "ai:memory.read",
      "ai:knowledge.ingest",
      "ai:model.registry.read",
      "ai:model.router.read",
      "ai:provider.registry.read",
      "ai:identity.read",
      "ai:evaluation.read",
      "ai:risk.register.read",
      "ai:risk.register.manage",
      "ai:compliance.read",
      "ai:compliance.write",
      "ai:compliance.audit",
      "ai:compliance.certification",
      "ai:compliance.metrics",
      "agriculture:data.read",
    ],
  },
  FAMILY_OFFICE_PRINCIPAL: {
    name: "Family Office Principal",
    description: "Family governance, lineage verification, beneficiary oversight and vault custody.",
    scope: "ENTERPRISE",
    privileged: true,
    permissions: [
      "platform:dashboard.read",
      "organization:entity.read",
      "organization:ownership.read",
      "governance:body.read",
      "governance:resolution.read",
      "governance:resolution.propose",
      "governance:resolution.vote",
      "family:member.read",
      "family:member.manage",
      "family:beneficiary.read",
      "family:beneficiary.manage",
      "family:vault.read",
      // Capital & wealth domain (§38). The Principal sees and records the whole
      // domain, and decides nothing: every `.manage` here is a governed record,
      // and committee decisions require `familyoffice:committee.decide` plus an
      // authority reference, which this role deliberately does NOT hold.
      "familyoffice:capital.read",
      "familyoffice:capital.manage",
      "familyoffice:investment.read",
      "familyoffice:investment.manage",
      "familyoffice:obligation.read",
      "familyoffice:obligation.manage",
      "familyoffice:realestate.read",
      "familyoffice:realestate.manage",
      "familyoffice:treasury.read",
      "familyoffice:cashflow.read",
      "familyoffice:risk.read",
      "familyoffice:liquidity.read",
      "familyoffice:scenario.read",
      "familyoffice:scenario.simulate",
      "familyoffice:capitalrequest.read",
      "familyoffice:capitalrequest.manage",
      "familyoffice:committee.read",
      "familyoffice:decisionjournal.read",
      "familyoffice:decisionjournal.manage",
      "familyoffice:intelligence.read",
      "familyoffice:intelligence.manage",
      "familyoffice:generational.read",
      "familyoffice:generational.manage",
      "familyoffice:education.read",
      "familyoffice:education.manage",
      // Protection & insurance: the Principal records and governs the whole
      // domain — designations included — and nothing here bypasses the MFA
      // step-up on `familyoffice:beneficiary.manage` or the finance boundary.
      "familyoffice:protection.read",
      "familyoffice:protection.manage",
      "familyoffice:beneficiary.manage",
      "familyoffice:claim.read",
      "familyoffice:claim.manage",
      "documents:registry.read",
      "ai:noelia.query",
      "ai:executive.read",
      "ai:memory.read",
    ],
  },
  /**
   * Family Office Director — runs the office day to day.
   *
   * Read across the capital & wealth domain plus the recording permissions, but
   * NOT `familyoffice:committee.decide` and NOT `familyoffice:capital.postmortem` outcome
   * attribution: running the office is not deciding for it (§40 segregation of
   * duties — requester ≠ approver).
   */
  FAMILY_OFFICE_DIRECTOR: {
    name: "Family Office Director",
    description: "Operates the Family Office capital, wealth and treasury domain. Records and reports; does not approve.",
    scope: "ENTERPRISE",
    privileged: false,
    permissions: [
      "platform:dashboard.read",
      "organization:entity.read",
      "family:member.read",
      "familyoffice:capital.read",
      "familyoffice:capital.manage",
      "familyoffice:investment.read",
      "familyoffice:investment.manage",
      "familyoffice:obligation.read",
      "familyoffice:obligation.manage",
      "familyoffice:realestate.read",
      "familyoffice:realestate.manage",
      "familyoffice:treasury.read",
      "familyoffice:cashflow.read",
      "familyoffice:risk.read",
      "familyoffice:liquidity.read",
      "familyoffice:scenario.read",
      "familyoffice:scenario.simulate",
      "familyoffice:capitalrequest.read",
      "familyoffice:capitalrequest.manage",
      "familyoffice:committee.read",
      "familyoffice:decisionjournal.read",
      "familyoffice:decisionjournal.manage",
      "familyoffice:intelligence.read",
      "familyoffice:intelligence.manage",
      "familyoffice:generational.read",
      "familyoffice:education.read",
      "familyoffice:education.manage",
      // Protection & insurance: records and reports; the domain carries no
      // approval permission at all (claim transitions record FACTS; the
      // insurer decides, and designation changes stay under MFA step-up).
      "familyoffice:protection.read",
      "familyoffice:protection.manage",
      "familyoffice:beneficiary.manage",
      "familyoffice:claim.read",
      "familyoffice:claim.manage",
      "documents:registry.read",
      "ai:noelia.query",
    ],
  },
  /** Investment Officer — builds the case; never approves it. */
  INVESTMENT_OFFICER: {
    name: "Investment Officer",
    description: "Builds investment cases, theses and models for committee review. Has no approval authority.",
    scope: "ENTITY",
    privileged: false,
    permissions: [
      "organization:entity.read",
      "familyoffice:capital.read",
      "familyoffice:investment.read",
      "familyoffice:investment.manage",
      "familyoffice:obligation.read",
      "familyoffice:realestate.read",
      "familyoffice:realestate.manage",
      "familyoffice:cashflow.read",
      "familyoffice:risk.read",
      "familyoffice:scenario.read",
      "familyoffice:scenario.simulate",
      "familyoffice:capitalrequest.read",
      "familyoffice:capitalrequest.manage",
      "familyoffice:decisionjournal.read",
      "familyoffice:decisionjournal.manage",
      "familyoffice:intelligence.read",
      "familyoffice:protection.read",
      "documents:registry.read",
      "ai:noelia.query",
    ],
  },
  /** Treasury Officer — liquidity, cash and debt service. */
  TREASURY_OFFICER: {
    name: "Treasury Officer",
    description: "Family Office treasury, liquidity and debt-service monitoring. Read and project; never transfer.",
    scope: "ENTITY",
    privileged: false,
    permissions: [
      "organization:entity.read",
      "finance:treasury.read",
      "familyoffice:capital.read",
      "familyoffice:treasury.read",
      "familyoffice:cashflow.read",
      "familyoffice:liquidity.read",
      "familyoffice:obligation.read",
      "familyoffice:obligation.manage",
      "familyoffice:risk.read",
      "familyoffice:scenario.read",
      "familyoffice:scenario.simulate",
      "familyoffice:intelligence.read",
      "familyoffice:protection.read",
      "familyoffice:claim.read",
      "ai:noelia.query",
    ],
  },
  /** Risk Officer — stress, concentration and the financial red line. */
  RISK_OFFICER: {
    name: "Family Office Risk Officer",
    description: "Family Office risk, stress testing and financial red-line reporting. Advisory; no approval authority.",
    scope: "ENTERPRISE",
    privileged: false,
    permissions: [
      "organization:entity.read",
      "risk:register.read",
      "familyoffice:capital.read",
      "familyoffice:investment.read",
      "familyoffice:obligation.read",
      "familyoffice:realestate.read",
      "familyoffice:treasury.read",
      "familyoffice:cashflow.read",
      "familyoffice:risk.read",
      "familyoffice:liquidity.read",
      "familyoffice:scenario.read",
      "familyoffice:scenario.simulate",
      "familyoffice:intelligence.read",
      "familyoffice:intelligence.manage",
      "familyoffice:protection.read",
      "familyoffice:claim.read",
      "ai:noelia.query",
    ],
  },
  /**
   * Legal Reviewer — clears the LEGAL_REVIEW gate and nothing else.
   *
   * Deliberately narrow: a reviewer who could also approve would be able to
   * clear their own review, which is the collapse of duties §40 forbids.
   */
  LEGAL_REVIEWER: {
    name: "Legal Reviewer",
    description: "Records legal review against Family Office matters. Review authority only; no approval authority.",
    scope: "ENTERPRISE",
    privileged: false,
    permissions: [
      "legal:matter.read",
      "legal:matter.manage",
      "familyoffice:capitalrequest.read",
      "familyoffice:investment.read",
      "familyoffice:obligation.read",
      "familyoffice:realestate.read",
      "familyoffice:intelligence.read",
      "familyoffice:protection.read",
      "familyoffice:claim.read",
      "documents:registry.read",
    ],
  },
  /**
   * Tax Reviewer — clears the TAX_REVIEW gate and nothing else.
   *
   * May record at PROFESSIONAL_REVIEW level; may NEVER record
   * FINAL_ACCOUNTING_TREATMENT, which is Finance OS's (§22, §32).
   */
  TAX_REVIEWER: {
    name: "Tax Reviewer",
    description: "Records tax review and tax positions at ASSUMPTION, ESTIMATE, CURRENT_RULE or PROFESSIONAL_REVIEW level. Never asserts final accounting treatment.",
    scope: "ENTERPRISE",
    privileged: false,
    permissions: [
      "finance:tax.read",
      "familyoffice:capitalrequest.read",
      "familyoffice:investment.read",
      "familyoffice:obligation.read",
      "familyoffice:realestate.read",
      "familyoffice:intelligence.read",
      "familyoffice:intelligence.manage",
      "familyoffice:protection.read",
      "documents:registry.read",
    ],
  },
  /**
   * Investment Committee Member — the approval seat.
   *
   * Holds `familyoffice:committee.decide`, which requires an authority reference
   * (a resolution or approval instrument) on every decision. Deliberately does
   * NOT hold `familyoffice:capitalrequest.manage`: the committee must not be able to
   * raise the matter it then approves (§40).
   */
  INVESTMENT_COMMITTEE_MEMBER: {
    name: "Investment Committee Member",
    description: "Reviews and decides Family Office capital allocations under a recorded authority instrument. Cannot raise the matter it decides.",
    scope: "ENTERPRISE",
    privileged: true,
    permissions: [
      "organization:entity.read",
      "governance:body.read",
      "governance:resolution.read",
      "governance:resolution.vote",
      "familyoffice:capital.read",
      "familyoffice:investment.read",
      "familyoffice:obligation.read",
      "familyoffice:realestate.read",
      "familyoffice:cashflow.read",
      "familyoffice:risk.read",
      "familyoffice:liquidity.read",
      "familyoffice:scenario.read",
      "familyoffice:capitalrequest.read",
      "familyoffice:committee.read",
      "familyoffice:committee.decide",
      "familyoffice:decisionjournal.read",
      "familyoffice:capital.postmortem",
      "familyoffice:generational.read",
      "familyoffice:protection.read",
      "documents:registry.read",
      "ai:noelia.query",
    ],
  },
  /** Family Analyst — read and model, no recording authority beyond scenarios. */
  FAMILY_ANALYST: {
    name: "Family Office Analyst",
    description: "Analyses and models the Family Office capital position. Read plus simulation; records nothing authoritative.",
    scope: "ENTITY",
    privileged: false,
    permissions: [
      "organization:entity.read",
      "familyoffice:capital.read",
      "familyoffice:investment.read",
      "familyoffice:obligation.read",
      "familyoffice:realestate.read",
      "familyoffice:treasury.read",
      "familyoffice:cashflow.read",
      "familyoffice:risk.read",
      "familyoffice:liquidity.read",
      "familyoffice:scenario.read",
      "familyoffice:scenario.simulate",
      "familyoffice:capitalrequest.read",
      "familyoffice:committee.read",
      "familyoffice:decisionjournal.read",
      "familyoffice:intelligence.read",
      "familyoffice:generational.read",
      "familyoffice:education.read",
      "familyoffice:protection.read",
      "familyoffice:claim.read",
      "ai:noelia.query",
    ],
  },
  /**
   * Family Member (read only) — the least-privilege seat.
   *
   * Sees the education curriculum and their own generational position, and
   * nothing else. No capital, investment, obligation, debt or liquidity data:
   * a read-only family seat is not a read-only analyst seat.
   */
  FAMILY_MEMBER_VIEW: {
    name: "Family Member (read only)",
    description: "Read-only access to family education and their own generational position. No capital, investment or debt data.",
    scope: "ENTITY",
    privileged: false,
    permissions: ["family:member.read", "familyoffice:education.read", "familyoffice:generational.read"],
  },
  HCM_DIRECTOR: {
    name: "Group HCM Director",
    description: "Single source of truth for the workforce lifecycle.",
    scope: "ENTERPRISE",
    privileged: false,
    permissions: [
      "platform:dashboard.read",
      "organization:entity.read",
      "hcm:employee.read",
      "hcm:employee.manage",
      "governance:policy.read",
      "documents:registry.read",
      "ai:noelia.query",
      "ai:executive.read",
      "ai:analytics.read",
      "ai:memory.read",
    ],
  },
  SECTOR_OPERATOR: {
    name: "Sector OS Operator",
    description: "Operational execution inside a single Sector OS under BEYU OS governance.",
    scope: "SECTOR",
    privileged: false,
    permissions: [
      "platform:dashboard.read",
      "organization:entity.read",
      "hcm:employee.read",
      "finance:capital.read",
      "risk:register.read",
      "compliance:obligation.read",
      "documents:registry.read",
      // Sector operational government submissions (NHIF folios, DHIS2 reports)
      // through the canonical gateway; HIGH_RISK so MFA step-up applies.
      "government:integration.read",
      "government:submission.manage",
      "agriculture:data.read",
      "agriculture:data.manage",
      "foundation:program.read",
      "foundation:compliance.read",
      "foundation:impact.read",
      "ai:noelia.query",
      "ai:executive.read",
      "ai:analytics.read",
    ],
  },
  FOUNDATION_DIRECTOR: {
    name: "Foundation Director",
    description: "Accountable executive for a foundation tenant: lifecycle, governance, material grants and investments.",
    scope: "SECTOR",
    privileged: true,
    permissions: [
      "platform:dashboard.read",
      "organization:entity.read",
      "governance:body.read",
      "governance:resolution.read",
      "governance:resolution.propose",
      "governance:resolution.vote",
      "risk:register.read",
      "risk:register.manage",
      "compliance:obligation.read",
      "legal:matter.read",
      "hcm:employee.read",
      "documents:registry.read",
      "documents:registry.manage",
      "foundation:registry.read",
      "foundation:registry.manage",
      "foundation:formation.read",
      "foundation:formation.manage",
      "foundation:structure.read",
      "foundation:structure.manage",
      "foundation:structure.simulate",
      "foundation:governance.read",
      "foundation:governance.manage",
      "foundation:tax.read",
      "foundation:tax.assess",
      "foundation:compliance.read",
      "foundation:compliance.manage",
      "foundation:donor.read",
      "foundation:donor.manage",
      "foundation:fund.read",
      "foundation:fund.manage",
      "foundation:grant.read",
      "foundation:grant.manage",
      "foundation:grant.approve",
      "foundation:program.read",
      "foundation:program.manage",
      "foundation:beneficiary.read",
      "foundation:beneficiary.manage",
      "foundation:procurement.read",
      "foundation:procurement.manage",
      "foundation:asset.read",
      "foundation:asset.manage",
      "foundation:investment.read",
      "foundation:investment.manage",
      "foundation:investment.approve",
      "foundation:safeguarding.read",
      "foundation:safeguarding.manage",
      "foundation:impact.read",
      "foundation:impact.manage",
      "foundation:assignment.read",
      "foundation:assignment.manage",
      "audit:log.read",
      "audit:event.read",
      "ai:noelia.query",
      "ai:executive.read",
      "ai:analytics.read",
      "ai:memory.read",
    ],
  },
  FOUNDATION_OFFICER: {
    name: "Foundation Officer",
    description: "Day-to-day foundation operations. Cannot approve material grants or investments.",
    scope: "SECTOR",
    privileged: false,
    permissions: [
      "platform:dashboard.read",
      "organization:entity.read",
      "governance:resolution.read",
      "risk:register.read",
      "compliance:obligation.read",
      "hcm:employee.read",
      "documents:registry.read",
      "documents:registry.manage",
      "foundation:registry.read",
      "foundation:formation.read",
      "foundation:formation.manage",
      "foundation:structure.read",
      "foundation:structure.simulate",
      "foundation:governance.read",
      "foundation:governance.manage",
      "foundation:tax.read",
      "foundation:compliance.read",
      "foundation:compliance.manage",
      "foundation:donor.read",
      "foundation:donor.manage",
      "foundation:fund.read",
      "foundation:grant.read",
      "foundation:grant.manage",
      "foundation:program.read",
      "foundation:program.manage",
      "foundation:beneficiary.read",
      "foundation:beneficiary.manage",
      "foundation:procurement.read",
      "foundation:procurement.manage",
      "foundation:asset.read",
      "foundation:asset.manage",
      "foundation:investment.read",
      "foundation:safeguarding.read",
      "foundation:impact.read",
      "foundation:impact.manage",
      "foundation:assignment.read",
      "ai:noelia.query",
      "ai:executive.read",
      "ai:analytics.read",
    ],
  },
  AUDITOR: {
    name: "Internal Auditor",
    description: "Read-only assurance access across the control plane. Cannot mutate any record.",
    scope: "ENTERPRISE",
    privileged: false,
    permissions: [
      "platform:dashboard.read",
      "platform:registry.read",
      "organization:entity.read",
      "organization:ownership.read",
      "governance:body.read",
      "governance:resolution.read",
      "governance:policy.read",
      "risk:register.read",
      "compliance:obligation.read",
      "legal:matter.read",
      "finance:ledger.read",
      "finance:treasury.read",
      "finance:capital.read",
      "finance:waterfall.read",
      "finance:tax.read",
      "finance:payments.read",
      "government:integration.read",
      "hcm:employee.read",
      "documents:registry.read",
      "audit:log.read",
      "audit:event.read",
      "ai:executive.read",
      "ai:analytics.read",
      "ai:memory.read",
      "ai:workflow.approve",
      "ai:model.registry.read",
      "ai:model.router.read",
      "ai:provider.registry.read",
      "ai:identity.read",
      "ai:evaluation.read",
      "ai:risk.register.read",
      "agriculture:data.read",
    ],
  },
};

/** Classification ceiling per role — ABAC dimension enforced at read time. */
export const ROLE_CLEARANCE: Record<string, Classification> = {
  PLATFORM_ADMIN: "RESTRICTED",
  GROUP_CEO: "HIGHLY_RESTRICTED",
  GROUP_CFO: "RESTRICTED",
  CHIEF_GOVERNANCE_OFFICER: "HIGHLY_RESTRICTED",
  CHIEF_RISK_COMPLIANCE: "RESTRICTED",
  FAMILY_OFFICE_PRINCIPAL: "HIGHLY_RESTRICTED",
  // Family Office capital & wealth seats. Clearance is granted on need, not on
  // seniority: the committee member and the director see the capital domain at
  // HIGHLY_RESTRICTED because the decision journal and generational plans live
  // there, while the reviewer seats are capped at RESTRICTED because a reviewer
  // needs the matter, not the family's private reasoning.
  FAMILY_OFFICE_DIRECTOR: "HIGHLY_RESTRICTED",
  INVESTMENT_OFFICER: "RESTRICTED",
  TREASURY_OFFICER: "RESTRICTED",
  RISK_OFFICER: "RESTRICTED",
  LEGAL_REVIEWER: "RESTRICTED",
  TAX_REVIEWER: "RESTRICTED",
  INVESTMENT_COMMITTEE_MEMBER: "HIGHLY_RESTRICTED",
  FAMILY_ANALYST: "RESTRICTED",
  FAMILY_MEMBER_VIEW: "HIGHLY_RESTRICTED",
  HCM_DIRECTOR: "RESTRICTED",
  SECTOR_OPERATOR: "CONFIDENTIAL",
  AUDITOR: "RESTRICTED",
};
