import "dotenv/config";
import "../setup-env";
import { test, expect } from "@playwright/test";
import { eq } from "drizzle-orm";
import { db } from "../../src/db";
import { governanceAppointments, governanceMembers } from "../../src/db/schema";
import { nominateMember } from "../../src/lib/governance/appointment-service";
import { login } from "../helpers/http";
import { appointmentFixture, appointmentInput, appointmentBallot, asAppointmentActor as as, cleanupAppointments } from "../helpers/appointments";
import { withReboundAppointmentActors } from "../helpers/appointment-identity";
let f: Awaited<ReturnType<typeof appointmentFixture>>;
test.beforeAll(async () => { await cleanupAppointments("APPT_ORIGIN_BROWSER"); f = await appointmentFixture("APPT_ORIGIN_BROWSER"); });
test.afterAll(() => cleanupAppointments("APPT_ORIGIN_BROWSER"));
test("stale approval UI cannot erase the original nominator through identity rebinding", async ({ page, context, baseURL }) => {
 test.setTimeout(150000);
 const a = await as(f.chair, () => nominateMember(f.chair, f.bodyId, appointmentInput(f.candidate.userId), { traceId: "APPOINTMENT_ORIGIN_BROWSER" }));
 const resolutionId = await appointmentBallot(a.id, f.chair);
 const cookie = await login(f.secretary.email);
 await context.addCookies(cookie.split("; ").map((s) => { const i = s.indexOf("="); return { name: s.slice(0,i), value: s.slice(i+1), url: baseURL! }; }));
 await page.goto("/os/governance");
 const panel = page.locator(`[data-appointment-body="${f.bodyId}"]`); await panel.locator("summary").click();
 const card = panel.locator(`[data-appointment-id="${a.id}"]`);
 await card.getByLabel("Appointment review / consent note").fill("Original-human independence is evaluated by the backend");
 await card.getByLabel("Approved nomination-specific APPOINTMENT resolution ID").fill(resolutionId);
 const button = card.getByRole("button", { name: "Record independent appointment approval" });
 let deniedKey: string | null = null;
 await withReboundAppointmentActors(f, async () => {
  const denied = page.waitForResponse((r) => r.url().endsWith(`/appointments/${a.id}`) && r.request().method() === "POST");
  await button.click(); const rejection = await denied; expect(rejection.status()).toBe(403); deniedKey = await rejection.request().headerValue("idempotency-key");
  await expect(panel.getByRole("status")).toContainText("nominating person");
  expect((await db.select().from(governanceAppointments).where(eq(governanceAppointments.id, a.id)))[0]).toMatchObject({ status: "NOMINATED", revision: 1, nominatedByPartyId: f.chair.partyId, approvedByPartyId: null });
 });
 const approved = page.waitForResponse((r) => r.url().endsWith(`/appointments/${a.id}`) && r.request().method() === "POST");
 await button.click(); const approval = await approved; expect(approval.status()).toBe(200); expect(await approval.request().headerValue("idempotency-key")).toBe(deniedKey);
 await expect(card).toContainText("APPROVED");
 await page.reload(); await panel.locator("summary").click(); await expect(card).toContainText("APPROVED");
 expect((await db.select().from(governanceAppointments).where(eq(governanceAppointments.id, a.id)))[0]).toMatchObject({ nominatedByPartyId: f.chair.partyId, approvedByPartyId: f.secretary.partyId });
 expect(await db.select().from(governanceMembers).where(eq(governanceMembers.partyId, f.candidate.partyId!))).toHaveLength(0);
});
