import "dotenv/config";
import "../setup-env";
import { test, expect } from "@playwright/test";
import { eq } from "drizzle-orm";
import { db } from "../../src/db";
import { governanceCharters, governanceBodies, governanceMembers, roleAssignments } from "../../src/db/schema";
import { apiPost, login } from "../helpers/http";
import { concludedCharterBallot } from "../helpers/charters";
import { initialCharterFixture } from "../helpers/initial-charters";
import { cleanupEstablishments } from "../helpers/establishments";
let f: Awaited<ReturnType<typeof initialCharterFixture>>;
let id: string, resolutionId: string, chair: string, secretary: string;
test.beforeAll(async () => { test.setTimeout(120000); await cleanupEstablishments("INITIAL_CHARTER_BROWSER"); f = await initialCharterFixture("INITIAL_CHARTER_BROWSER"); chair = await login("ceo@beyu.os"); secretary = await login("governance@beyu.os"); });
test.afterAll(() => cleanupEstablishments("INITIAL_CHARTER_BROWSER"));
test("superior approves a dormant charter; stale expired-authority UI is denied and no body activation occurs", async ({ page, context, baseURL }) => {
 test.setTimeout(180000);
 async function identity(cookie: string) { await context.clearCookies(); await context.addCookies(cookie.split("; ").map((s) => { const i = s.indexOf("="); return { name: s.slice(0,i), value: s.slice(i+1), url: baseURL! }; })); }
 await identity(chair); await page.goto("/os/governance");
 await expect(page.locator(`[data-appointment-body="${f.childId}"]`).getByRole("button", { name: "Nominate a body member" })).toHaveCount(0);
 const panel = page.locator(`[data-charter-body="${f.childId}"]`); await panel.locator("summary").click();
 await panel.getByLabel("Charter document ID", { exact: true }).fill("DOC_D4");
 await panel.getByLabel("Charter purpose / terms of reference").fill("Browser adoption of independently reviewed board terms and composition requirements");
 const creating = page.waitForResponse((r) => r.url().endsWith(`/${f.childId}/charters`) && r.request().method() === "POST");
 await panel.getByRole("button", { name: "Create charter version", exact: true }).click();
 const response = await creating; expect(response.status()).toBe(201); id = (await response.json()).data.id;
 const card = panel.locator(`[data-charter-id="${id}"]`); await expect(card).toContainText("DRAFT");
 await card.getByLabel("Review note").fill("Submit complete terms for independent review");
 const submitted = page.waitForResponse((r) => r.url().endsWith(`/charters/${id}`));
 await card.getByRole("button", { name: "Submit charter for review" }).click(); expect((await submitted).status()).toBe(200);
 await expect(card).toContainText("IN_REVIEW"); await expect(card.getByRole("button", { name: "Record superior charter approval" })).toHaveCount(0);
 resolutionId = await concludedCharterBallot(id);
 expect((await apiPost(`/api/v1/governance/resolutions/${resolutionId}/decision`, {}, { cookie: chair })).status).toBe(200);
 await identity(secretary); await page.reload(); await panel.locator("summary").click();
 await card.getByLabel("Review note").fill("Independently record the approved charter adoption");
 await card.getByLabel("Approved charter-specific POLICY resolution ID").fill(resolutionId);
 let deniedKey: string | null = null;
 const grants = await db.select().from(roleAssignments).where(eq(roleAssignments.userId, f.secretary.userId));
 await db.update(roleAssignments).set({ effectiveTo: "2000-01-01" }).where(eq(roleAssignments.userId, f.secretary.userId));
 try {
  const denied = page.waitForResponse((r) => r.url().endsWith(`/charters/${id}`));
  await card.getByRole("button", { name: "Record superior charter approval" }).click();
  const rejection = await denied; expect(rejection.status()).toBe(403); deniedKey = await rejection.request().headerValue("idempotency-key");
  expect((await db.select().from(governanceCharters).where(eq(governanceCharters.id, id)))[0].status).toBe("IN_REVIEW");
 } finally { for (const grant of grants) await db.update(roleAssignments).set({ effectiveTo: grant.effectiveTo }).where(eq(roleAssignments.id, grant.id)); }
 const adopting = page.waitForResponse((r) => r.url().endsWith(`/charters/${id}`)); await card.getByRole("button", { name: "Record superior charter approval" }).click(); const approval = await adopting; expect(approval.status()).toBe(200); expect(await approval.request().headerValue("idempotency-key")).toBe(deniedKey);
 await expect(card).toContainText("APPROVED"); await page.reload(); await panel.locator("summary").click(); await expect(card).toContainText("APPROVED");
 await expect(panel).toContainText("Initial charter approved, not effective");
 const [record] = await db.select().from(governanceCharters).where(eq(governanceCharters.id, id)); expect(record.adoptedByUserId).toBe("USR_GRACE_KILELE"); expect(record.resolutionId).toBe(resolutionId);
 expect(record.authorityBodyId).toBe(f.bodyId);
 expect((await db.select().from(governanceBodies).where(eq(governanceBodies.id, f.childId)))[0].status).toBe("DRAFT");
 expect(await db.select().from(governanceMembers).where(eq(governanceMembers.bodyId, f.childId))).toHaveLength(0);
});
