import "dotenv/config";
import "../setup-env";
import { test, expect } from "@playwright/test";
import { eq } from "drizzle-orm";
import { db } from "../../src/db";
import { governanceMembers } from "../../src/db/schema";
import { login } from "../helpers/http";
import { appointmentFixture, appointmentBallot, cleanupAppointments } from "../helpers/appointments";
let f: Awaited<ReturnType<typeof appointmentFixture>>;
test.beforeAll(async () => { await cleanupAppointments("APPT_BROWSER"); f = await appointmentFixture("APPT_BROWSER"); });
test.afterAll(() => cleanupAppointments("APPT_BROWSER"));
test("nomination, independent approval, human consent and activation survive reload", async ({ page, context, baseURL }) => {
 test.setTimeout(150000);
 async function identity(email: string) { const cookie = await login(email); await context.clearCookies(); await context.addCookies(cookie.split("; ").map((s) => { const i = s.indexOf("="); return { name: s.slice(0,i), value: s.slice(i+1), url: baseURL! }; })); await page.goto("/os/governance"); }
 await identity(f.chair.email); const panel = page.locator(`[data-appointment-body="${f.bodyId}"]`); await panel.locator("summary").click();
 await panel.getByLabel("Nominee user ID").fill(f.candidate.userId); await panel.getByLabel("Appointment instrument document ID").fill("DOC_D4");
 await panel.getByLabel("Term start").fill(new Date().toISOString().slice(0,10)); await panel.getByLabel("Term end (inclusive)").fill("2030-12-31");
 await panel.getByLabel("Nomination rationale and evidence review").fill("Reviewed the documented eligibility and term of this nominee");
 const created = page.waitForResponse((r) => r.url().endsWith(`/${f.bodyId}/appointments`) && r.request().method() === "POST");
 await panel.getByRole("button", { name: "Nominate a body member" }).click(); const response = await created; expect(response.status()).toBe(201); const id = (await response.json()).data.id;
 const resolutionId = await appointmentBallot(id, f.chair);
 await identity(f.secretary.email); await panel.locator("summary").click(); const card = panel.locator(`[data-appointment-id="${id}"]`);
 await card.getByLabel("Appointment review / consent note").fill("Independent review of the approved appointment");
 await card.getByLabel("Approved nomination-specific APPOINTMENT resolution ID").fill(resolutionId);
 await card.getByRole("button", { name: "Record independent appointment approval" }).click(); await expect(card).toContainText("APPROVED");
 await identity(f.candidate.email); await panel.locator("summary").click(); await card.getByLabel("Appointment review / consent note").fill("I accept the documented duties and bounded appointment term");
 await card.getByRole("button", { name: "Accept appointment terms" }).click(); await expect(card).toContainText("ACCEPTED");
 await expect(card.getByRole("button", { name: "Activate canonical membership" })).toHaveCount(0);
 await identity(f.secretary.email); await panel.locator("summary").click(); await card.getByLabel("Appointment review / consent note").fill("Rechecked current authority and composition before activation");
 await card.getByRole("button", { name: "Activate canonical membership" }).click(); await expect(card).toContainText("ACTIVE");
 await page.reload(); await panel.locator("summary").click(); await expect(card).toContainText("Canonical membership:");
 expect(await db.select().from(governanceMembers).where(eq(governanceMembers.partyId, f.candidate.partyId!))).toHaveLength(1);
});
