/**
 * BEYU Federation & Trust — TANZANIA domain taxonomy (data, program §14).
 * Canonical domains for the TZ jurisdiction profile. The taxonomy is data:
 * future jurisdictions carry their own domain sets; the core is generic.
 */
export const TZ_DOMAINS: { code: string; displayName: string; parentCode?: string }[] = [
  { code: "IDENTITY", displayName: "Identity" },
  { code: "CIVIL_STATUS", displayName: "Civil Status" },
  { code: "IMMIGRATION", displayName: "Immigration" },
  { code: "CORPORATE", displayName: "Corporate" },
  { code: "BENEFICIAL_OWNERSHIP", displayName: "Beneficial Ownership", parentCode: "CORPORATE" },
  { code: "TAX", displayName: "Tax", parentCode: "CORPORATE" },
  { code: "LICENSING", displayName: "Licensing", parentCode: "CORPORATE" },
  { code: "INVESTMENT", displayName: "Investment", parentCode: "CORPORATE" },
  { code: "INTELLECTUAL_PROPERTY", displayName: "Intellectual Property", parentCode: "CORPORATE" },
  { code: "EMPLOYMENT", displayName: "Employment" },
  { code: "SOCIAL_PROTECTION", displayName: "Social Protection" },
  { code: "HEALTH", displayName: "Health" },
  { code: "EDUCATION", displayName: "Education" },
  { code: "PROFESSIONAL_CREDENTIALS", displayName: "Professional Credentials" },
  { code: "ACCOUNTING_AUDIT", displayName: "Accounting & Audit" },
  { code: "FINANCE", displayName: "Finance" },
  { code: "INSURANCE", displayName: "Insurance" },
  { code: "CAPITAL_MARKETS", displayName: "Capital Markets" },
  { code: "PAYMENTS", displayName: "Payments" },
  { code: "AGRICULTURE", displayName: "Agriculture" },
  { code: "LIVESTOCK", displayName: "Livestock" },
  { code: "FISHERIES", displayName: "Fisheries" },
  { code: "UJENZI", displayName: "Ujenzi (Construction/Engineering)" },
  { code: "LAND", displayName: "Land" },
  { code: "PROPERTY", displayName: "Property" },
  { code: "WATER", displayName: "Water" },
  { code: "ENERGY", displayName: "Energy" },
  { code: "MINING", displayName: "Mining" },
  { code: "ENVIRONMENT", displayName: "Environment" },
  { code: "NATURAL_RESOURCES", displayName: "Natural Resources" },
  { code: "TRANSPORT", displayName: "Transport" },
  { code: "SUPPLY_CHAIN_LOGISTICS", displayName: "Supply Chain & Logistics" },
  { code: "COMMUNICATIONS", displayName: "Communications" },
  { code: "DIGITAL_GOVERNMENT", displayName: "Digital Government" },
  { code: "POSTAL", displayName: "Postal" },
  { code: "TRADE", displayName: "Trade" },
  { code: "CUSTOMS_BORDER", displayName: "Customs & Border" },
  { code: "INDUSTRY", displayName: "Industry" },
  { code: "STANDARDS", displayName: "Standards" },
  { code: "CONSUMER_PROTECTION", displayName: "Consumer Protection" },
  { code: "PRODUCT_SAFETY", displayName: "Product Safety" },
  { code: "PROCUREMENT", displayName: "Procurement" },
  { code: "GOVERNMENT_PROCUREMENT", displayName: "Government Procurement", parentCode: "PROCUREMENT" },
  { code: "TOURISM", displayName: "Tourism" },
  { code: "CULTURE", displayName: "Culture" },
  { code: "SPORTS", displayName: "Sports" },
  { code: "MEDIA", displayName: "Media" },
  { code: "LEGAL_JUSTICE", displayName: "Legal & Justice" },
  { code: "LABOUR_DISPUTES", displayName: "Labour Disputes" },
  { code: "GOVERNANCE", displayName: "Governance" },
  { code: "ANTI_CORRUPTION", displayName: "Anti-Corruption" },
  { code: "HUMAN_RIGHTS", displayName: "Human Rights" },
  { code: "PUBLIC_SERVICE", displayName: "Public Service" },
  { code: "DEFENCE_SECURITY", displayName: "Defence & Security" },
  { code: "STATISTICS", displayName: "Statistics" },
  { code: "RESEARCH_SCIENCE", displayName: "Research & Science" },
  { code: "TECHNOLOGY_INNOVATION", displayName: "Technology & Innovation" },
  { code: "EVIDENCE_PROVENANCE", displayName: "Evidence & Provenance" },
  { code: "DISASTER_EMERGENCY", displayName: "Disaster & Emergency" },
  { code: "BUSINESS_CONTINUITY", displayName: "Business Continuity" },
  { code: "CRITICAL_INFRASTRUCTURE", displayName: "Critical Infrastructure" },
  { code: "WEATHER_CLIMATE", displayName: "Weather & Climate" },
  { code: "FOOD_SECURITY", displayName: "Food Security" },
  { code: "INSPECTION_CERTIFICATION", displayName: "Inspection & Certification" },
  { code: "COMMUNITY_SOCIAL_SERVICES", displayName: "Community & Social Services" },
  { code: "YOUTH", displayName: "Youth" },
  { code: "GENDER_INCLUSION", displayName: "Gender & Inclusion" },
  { code: "NGOS_NONPROFIT", displayName: "NGOs & Nonprofit" },
  { code: "FOUNDATION_NONPROFIT", displayName: "Foundation & Nonprofit" },
  { code: "LOCAL_GOVERNMENT", displayName: "Local Government" },
  { code: "REGIONAL_ADMINISTRATION", displayName: "Regional Administration" },
  { code: "GEOSPATIAL_LOCATION", displayName: "Geospatial & Location" },
  { code: "DOCUMENT_RECORDS", displayName: "Document & Records" },
  { code: "TRUST_SERVICES", displayName: "Trust Services" },
  { code: "DATA_GOVERNANCE", displayName: "Data Governance" },
  { code: "DATA_EXCHANGE", displayName: "Data Exchange" },
  { code: "INTEROPERABILITY", displayName: "Interoperability" },
  { code: "FEDERATION_SECURITY", displayName: "Federation Security" },
  { code: "FEDERATION_GOVERNANCE", displayName: "Federation Governance" },
  { code: "INTERNATIONAL_CROSS_BORDER", displayName: "International & Cross-Border" },
];
