import type { InteropClassification } from "./contract";

/** Canonical enterprise domain identifiers. Sector codes are registered here, not implemented here. */
export const DOMAIN_CODES = [
  "IDENTITY",
  "GOVERNANCE",
  "AUTHORITY",
  "SECURITY",
  "HCM",
  "FINANCE",
  "TAX",
  "LEGAL",
  "CAPITAL",
  "TREASURY",
  "COMPLIANCE",
  "RISK",
  "AUDIT",
  "LINEAGE",
  "WORKFLOW",
  "AI",
  "HEALTH",
  "AGRICULTURE",
  "FOUNDATION",
] as const;
export type DomainCode = (typeof DOMAIN_CODES)[number];

export const DOMAIN_STATUS = [
  "COMPLETE",
  "PARTIAL",
  "REQUIRES_AUTHORITY",
  "DATA_NOT_AVAILABLE",
  "NOT_AVAILABLE",
] as const;
export type DomainStatus = (typeof DOMAIN_STATUS)[number];

export type DomainRegistryEntry = {
  domainId: string;
  domainCode: DomainCode;
  domainName: string;
  owner: string;
  systemOfRecord: string;
  dataClass: InteropClassification;
  apiContract: string[];
  eventContract: string[];
  authorityModel: string;
  securityModel: string;
  tenantModel: string;
  entityModel: string;
  traceModel: string;
  continuityClass: "LOCAL_ATOMIC" | "MULTI_STEP_GOVERNED" | "EVENTUAL" | "SIMULATION";
  dependencies: DomainCode[];
  status: DomainStatus;
};

const SHARED_API = ["common identity", "common authorization", "common trace envelope"];
const SHARED_EVENTS = ["DOMAIN_EVENT", "DOMAIN_STATUS"];

/**
 * One architecture registry for enterprise domains. This is metadata only: it
 * does not create a missing Sector OS or a second source-of-truth table.
 */
export const DOMAIN_REGISTRY: readonly DomainRegistryEntry[] = [
  {
    domainId: "DOM-IDENTITY",
    domainCode: "IDENTITY",
    domainName: "Identity Fabric",
    owner: "BEYU OS Kernel",
    systemOfRecord: "parties, users, sessions, roles, permissions",
    dataClass: "CONFIDENTIAL",
    apiContract: ["session resolution", "identity graph", ...SHARED_API],
    eventContract: ["USER_AUTHENTICATED", "DOMAIN_EVENT"],
    authorityModel: "common authority/permission model",
    securityModel: "RBAC + ABAC + MFA + tenant/entity scope",
    tenantModel: "canonical tenant scope",
    entityModel: "legal entity scope where applicable",
    traceModel: "server trace + correlation; actor is GlobalUserID",
    continuityClass: "LOCAL_ATOMIC",
    dependencies: ["SECURITY"],
    status: "PARTIAL",
  },
  {
    domainId: "DOM-GOVERNANCE",
    domainCode: "GOVERNANCE",
    domainName: "Constitutional Governance",
    owner: "BEYU OS Governance",
    systemOfRecord: "constitution_articles, policies, governance_bodies, resolutions",
    dataClass: "RESTRICTED",
    apiContract: ["governed resolution lifecycle", ...SHARED_API],
    eventContract: ["GOVERNANCE_RESOLUTION_PROPOSED", "GOVERNANCE_RESOLUTION_DECIDED", ...SHARED_EVENTS],
    authorityModel: "constitution → policy → decision → capability",
    securityModel: "common RBAC/ABAC + body membership + SoD",
    tenantModel: "tenant subtree with parent governance scope",
    entityModel: "governance body legal entity scope",
    traceModel: "mutation trace bound to audit/event pair",
    continuityClass: "MULTI_STEP_GOVERNED",
    dependencies: ["IDENTITY", "AUTHORITY", "SECURITY", "AUDIT"],
    status: "PARTIAL",
  },
  {
    domainId: "DOM-AUTHORITY",
    domainCode: "AUTHORITY",
    domainName: "Authority and Capability Gate",
    owner: "BEYU OS Kernel",
    systemOfRecord: "governance_decision_registry, governance_capability_registry",
    dataClass: "RESTRICTED",
    apiContract: ["6C activation", "scoped capability evaluation", ...SHARED_API],
    eventContract: ["DOMAIN_STATUS", ...SHARED_EVENTS],
    authorityModel: "one composed 6C/scoped authority model",
    securityModel: "fail closed on existence/effectiveness/scope/principal",
    tenantModel: "resolved tenant subtree",
    entityModel: "target legal entity and authority scope",
    traceModel: "authority explanation and operation trace",
    continuityClass: "LOCAL_ATOMIC",
    dependencies: ["IDENTITY", "GOVERNANCE", "SECURITY"],
    status: "REQUIRES_AUTHORITY",
  },
  {
    domainId: "DOM-SECURITY",
    domainCode: "SECURITY",
    domainName: "Security Kernel",
    owner: "BEYU OS Kernel",
    systemOfRecord: "identity/authz/session/audit controls",
    dataClass: "RESTRICTED",
    apiContract: ["guarded API", "tenant scope", "clearance filtering", ...SHARED_API],
    eventContract: ["USER_AUTHENTICATED", "DOMAIN_STATUS"],
    authorityModel: "common permission and authority gate",
    securityModel: "RBAC + ABAC + MFA + RLS defense in depth",
    tenantModel: "canonical tenant scope",
    entityModel: "canonical legal entity scope",
    traceModel: "request trace/correlation",
    continuityClass: "LOCAL_ATOMIC",
    dependencies: ["IDENTITY", "AUDIT"],
    status: "PARTIAL",
  },
  {
    domainId: "DOM-HCM",
    domainCode: "HCM",
    domainName: "Human Capital Management",
    owner: "HCM Director",
    systemOfRecord: "employees, employment_events, positions, org_units",
    dataClass: "RESTRICTED",
    apiContract: ["HCM workforce consumption", "employment observation", ...SHARED_API],
    eventContract: ["DOMAIN_EVENT", "DOMAIN_STATUS"],
    authorityModel: "common authority gate for lifecycle writes",
    securityModel: "common RBAC/ABAC + compensation clearance",
    tenantModel: "employing legal entity tenant within principal scope",
    entityModel: "employing legal entity",
    traceModel: "consumer request trace; source HCM master",
    continuityClass: "LOCAL_ATOMIC",
    dependencies: ["IDENTITY", "SECURITY", "GOVERNANCE"],
    status: "PARTIAL",
  },
  {
    domainId: "DOM-FINANCE",
    domainCode: "FINANCE",
    domainName: "Finance OS",
    owner: "Group CFO",
    systemOfRecord: "journal_entries, journal_lines, treasury_positions, capital_requests",
    dataClass: "RESTRICTED",
    apiContract: ["posting boundary", "financial read/analysis", ...SHARED_API],
    eventContract: ["JOURNAL_ENTRY_POSTED", "DOMAIN_STATUS", ...SHARED_EVENTS],
    authorityModel: "Governance → authority/capability → Finance execution",
    securityModel: "common RBAC/ABAC + financial controls + SoD",
    tenantModel: "tenant and legal-entity financial scope",
    entityModel: "legal entity and financial period",
    traceModel: "posting trace bound to ledger/audit/event",
    continuityClass: "LOCAL_ATOMIC",
    dependencies: ["IDENTITY", "GOVERNANCE", "AUTHORITY", "HCM", "AUDIT", "LINEAGE"],
    status: "REQUIRES_AUTHORITY",
  },
  {
    domainId: "DOM-TAX",
    domainCode: "TAX",
    domainName: "Tax Strategy and Compliance Intelligence",
    owner: "Finance OS / Tax Governance",
    systemOfRecord: "tax_strategies, tax_strategy_assessments",
    dataClass: "RESTRICTED",
    apiContract: ["candidate assessment", "jurisdiction-gated analysis", ...SHARED_API],
    eventContract: ["TAX_STRATEGY_ASSESSED", "DOMAIN_STATUS"],
    authorityModel: "tax governance authority; no liability invention",
    securityModel: "common RBAC/ABAC + jurisdiction/entity scope",
    tenantModel: "taxpayer tenant/entity scope",
    entityModel: "taxpayer legal entity and jurisdiction",
    traceModel: "assessment trace with strategy provenance",
    continuityClass: "MULTI_STEP_GOVERNED",
    dependencies: ["IDENTITY", "FINANCE", "GOVERNANCE", "LEGAL", "AUDIT"],
    status: "REQUIRES_AUTHORITY",
  },
  {
    domainId: "DOM-LEGAL",
    domainCode: "LEGAL",
    domainName: "Legal Evidence and Matters",
    owner: "Human legal governance",
    systemOfRecord: "legal_matters, documents, regulatory_changes",
    dataClass: "RESTRICTED",
    apiContract: ["legal matter read", "document/evidence registry", ...SHARED_API],
    eventContract: ["DOMAIN_STATUS", "DOMAIN_DOCUMENT"],
    authorityModel: "human legal authority; interpretation is not automated",
    securityModel: "common RBAC/ABAC + classification",
    tenantModel: "matter tenant scope",
    entityModel: "matter legal entity and jurisdiction",
    traceModel: "evidence/document provenance and operation trace",
    continuityClass: "MULTI_STEP_GOVERNED",
    dependencies: ["IDENTITY", "GOVERNANCE", "AUDIT"],
    status: "PARTIAL",
  },
  {
    domainId: "DOM-CAPITAL",
    domainCode: "CAPITAL",
    domainName: "Strategic Capital Allocation",
    owner: "BEYU OS Governance + Finance OS",
    systemOfRecord: "capital_requests, resolutions",
    dataClass: "RESTRICTED",
    apiContract: ["capital request governance prerequisite", ...SHARED_API],
    eventContract: ["CAPITAL_REQUEST_GOVERNANCE_AUTHORIZED", "DOMAIN_STATUS"],
    authorityModel: "Governance → capital authorization → Finance execution",
    securityModel: "common RBAC/ABAC + authority + entity reach",
    tenantModel: "capital request tenant scope",
    entityModel: "capital request legal entity",
    traceModel: "resolution/request/audit/event trace",
    continuityClass: "MULTI_STEP_GOVERNED",
    dependencies: ["GOVERNANCE", "AUTHORITY", "FINANCE", "AUDIT"],
    status: "REQUIRES_AUTHORITY",
  },
  {
    domainId: "DOM-TREASURY",
    domainCode: "TREASURY",
    domainName: "Treasury Observation and Settlement",
    owner: "Finance OS",
    systemOfRecord: "treasury_positions",
    dataClass: "RESTRICTED",
    apiContract: ["treasury observation", "reconciliation analysis", ...SHARED_API],
    eventContract: ["DOMAIN_STATUS"],
    authorityModel: "settlement requires governed capability",
    securityModel: "common RBAC/ABAC + attribution controls",
    tenantModel: "position tenant and legal entity",
    entityModel: "position legal entity",
    traceModel: "observation/reconciliation trace",
    continuityClass: "MULTI_STEP_GOVERNED",
    dependencies: ["IDENTITY", "FINANCE", "AUTHORITY", "AUDIT"],
    status: "DATA_NOT_AVAILABLE",
  },
  {
    domainId: "DOM-COMPLIANCE",
    domainCode: "COMPLIANCE",
    domainName: "Compliance Intelligence",
    owner: "Chief Risk and Compliance Officer",
    systemOfRecord: "compliance_obligations, compliance_assessments, controls",
    dataClass: "RESTRICTED",
    apiContract: ["compliance observation", "evidence assessment", ...SHARED_API],
    eventContract: ["DOMAIN_STATUS"],
    authorityModel: "human confirmation for authoritative assertions",
    securityModel: "common RBAC/ABAC + jurisdiction/entity scope",
    tenantModel: "obligation tenant scope",
    entityModel: "obligation legal entity",
    traceModel: "obligation/evidence/assessment trace",
    continuityClass: "MULTI_STEP_GOVERNED",
    dependencies: ["IDENTITY", "LEGAL", "GOVERNANCE", "AUDIT"],
    status: "PARTIAL",
  },
  {
    domainId: "DOM-RISK",
    domainCode: "RISK",
    domainName: "Risk Intelligence",
    owner: "Chief Risk and Compliance Officer",
    systemOfRecord: "risks, controls, anomaly_signals",
    dataClass: "RESTRICTED",
    apiContract: ["risk analysis", "risk observation", ...SHARED_API],
    eventContract: ["DOMAIN_STATUS"],
    authorityModel: "risk appetite/enforcement requires governance",
    securityModel: "common RBAC/ABAC + classification",
    tenantModel: "risk tenant scope",
    entityModel: "risk legal entity",
    traceModel: "risk/evidence trace",
    continuityClass: "MULTI_STEP_GOVERNED",
    dependencies: ["IDENTITY", "GOVERNANCE", "FINANCE", "AUDIT"],
    status: "PARTIAL",
  },
  {
    domainId: "DOM-AUDIT",
    domainCode: "AUDIT",
    domainName: "Audit Fabric",
    owner: "Internal Audit",
    systemOfRecord: "audit_log",
    dataClass: "RESTRICTED",
    apiContract: ["append audit", "verify chain", ...SHARED_API],
    eventContract: ["DOMAIN_STATUS"],
    authorityModel: "audit is evidence, not authority",
    securityModel: "append-only hash chain + immutable DB triggers",
    tenantModel: "audit tenant or explicit enterprise scope",
    entityModel: "entity carried in governed payload where applicable",
    traceModel: "trace/correlation linkage required for new events",
    continuityClass: "LOCAL_ATOMIC",
    dependencies: ["IDENTITY", "SECURITY"],
    status: "PARTIAL",
  },
  {
    domainId: "DOM-LINEAGE",
    domainCode: "LINEAGE",
    domainName: "Data Lineage",
    owner: "BEYU OS Data Governance",
    systemOfRecord: "financial lineage/provenance contracts",
    dataClass: "INTERNAL",
    apiContract: ["source/transformation/output provenance", ...SHARED_API],
    eventContract: ["DOMAIN_STATUS"],
    authorityModel: "lineage proves provenance; never grants authority",
    securityModel: "inherits common scope and classification",
    tenantModel: "source tenant scope",
    entityModel: "source entity scope",
    traceModel: "reverse trace through trace/correlation IDs",
    continuityClass: "LOCAL_ATOMIC",
    dependencies: ["AUDIT", "IDENTITY"],
    status: "PARTIAL",
  },
  {
    domainId: "DOM-WORKFLOW",
    domainCode: "WORKFLOW",
    domainName: "Workflow Primitive",
    owner: "BEYU OS Kernel",
    systemOfRecord: "governance workflows/workflow_instances/tasks",
    dataClass: "RESTRICTED",
    apiContract: ["transition evaluation", "SoD evaluation", ...SHARED_API],
    eventContract: ["DOMAIN_STATUS"],
    authorityModel: "delegates to common capability/authority gate",
    securityModel: "common RBAC/ABAC + role separation",
    tenantModel: "workflow tenant scope",
    entityModel: "workflow object entity scope",
    traceModel: "every transition requires trace",
    continuityClass: "MULTI_STEP_GOVERNED",
    dependencies: ["IDENTITY", "AUTHORITY", "AUDIT"],
    status: "PARTIAL",
  },
  {
    domainId: "DOM-AI",
    domainCode: "AI",
    domainName: "Noelia / HIVE Intelligence",
    owner: "AI Governance",
    systemOfRecord: "ai_decisions, knowledge_sources",
    dataClass: "RESTRICTED",
    apiContract: ["governed Noelia query", ...SHARED_API],
    eventContract: ["AI_DECISION_RECORDED", "DOMAIN_STATUS"],
    authorityModel: "inherits human principal; never self-authorizes",
    securityModel: "common RBAC/ABAC + policy + classification",
    tenantModel: "principal tenant scope",
    entityModel: "principal/request entity scope",
    traceModel: "request trace through decision/audit/event",
    continuityClass: "SIMULATION",
    dependencies: ["IDENTITY", "SECURITY", "GOVERNANCE", "AUDIT", "LINEAGE"],
    status: "PARTIAL",
  },
  {
    domainId: "DOM-HEALTH",
    domainCode: "HEALTH",
    domainName: "Health Sector OS",
    owner: "Sector OS owner under BEYU OS",
    systemOfRecord: "NOT_AVAILABLE in this repository",
    dataClass: "RESTRICTED",
    apiContract: ["consume identity/HCM/Finance/governance contracts"],
    eventContract: ["consume common DOMAIN_EVENT"],
    authorityModel: "BEYU OS authority above Sector OS",
    securityModel: "must consume common security model",
    tenantModel: "registered sector tenant",
    entityModel: "registered legal entity",
    traceModel: "common envelope required",
    continuityClass: "EVENTUAL",
    dependencies: ["IDENTITY", "HCM", "FINANCE", "GOVERNANCE", "SECURITY"],
    status: "NOT_AVAILABLE",
  },
  {
    domainId: "DOM-AGRICULTURE",
    domainCode: "AGRICULTURE",
    domainName: "Agriculture Sector OS",
    owner: "Sector OS owner under BEYU OS",
    systemOfRecord: "NOT_AVAILABLE in this repository",
    dataClass: "RESTRICTED",
    apiContract: ["consume identity/HCM/Finance/governance contracts"],
    eventContract: ["consume common DOMAIN_EVENT"],
    authorityModel: "BEYU OS authority above Sector OS",
    securityModel: "must consume common security model",
    tenantModel: "registered sector tenant",
    entityModel: "registered legal entity",
    traceModel: "common envelope required",
    continuityClass: "EVENTUAL",
    dependencies: ["IDENTITY", "HCM", "FINANCE", "GOVERNANCE", "SECURITY"],
    status: "NOT_AVAILABLE",
  },
  {
    domainId: "DOM-FOUNDATION",
    domainCode: "FOUNDATION",
    domainName: "Foundation Sector OS",
    owner: "Sector OS owner under BEYU OS",
    systemOfRecord: "foundation_programs",
    dataClass: "RESTRICTED",
    apiContract: ["consume common identity/HCM/Finance/governance contracts"],
    eventContract: ["consume common DOMAIN_EVENT"],
    authorityModel: "BEYU OS authority above Sector OS",
    securityModel: "must consume common security model",
    tenantModel: "foundation tenant scope",
    entityModel: "foundation legal entity",
    traceModel: "common envelope required",
    continuityClass: "EVENTUAL",
    dependencies: ["IDENTITY", "HCM", "FINANCE", "GOVERNANCE", "SECURITY"],
    status: "PARTIAL",
  },
];

export function domainRegistry(): DomainRegistryEntry[] {
  return DOMAIN_REGISTRY.map((entry) => ({
    ...entry,
    apiContract: [...entry.apiContract],
    eventContract: [...entry.eventContract],
    dependencies: [...entry.dependencies],
  }));
}

export function domainByCode(code: string): DomainRegistryEntry | null {
  return DOMAIN_REGISTRY.find((entry) => entry.domainCode === code) ?? null;
}
