// ─────────────────────────────────────────────────────────────────────────────
// Department Coverage Registry
// Master catalog of every hospital department BEYU Health OS must support,
// with the modules / capabilities required and an actual coverage assessment.
// ─────────────────────────────────────────────────────────────────────────────

export type Tier = "Tier 1" | "Tier 2" | "Tier 3" | "Tier 4" | "Tier 5" | "Tier 6";
export type CoverageStatus = "FULL" | "PARTIAL" | "ROADMAP";
export type Category =
  | "Clinical · Ambulatory"
  | "Clinical · Inpatient"
  | "Clinical · Critical Care"
  | "Clinical · Surgical"
  | "Clinical · Medical Specialty"
  | "Clinical · Surgical Specialty"
  | "Women & Child Health"
  | "Mental Health"
  | "Rehabilitation"
  | "Diagnostics · Imaging"
  | "Diagnostics · Laboratory"
  | "Diagnostics · Procedural"
  | "Treatment Services"
  | "Support Clinical"
  | "Administration"
  | "Facilities & Support"
  | "Specialized Units";

export interface Department {
  id: string;
  name: string;
  category: Category;
  /** Smallest facility tier where this dept is expected. */
  tier: Tier;
  /** Modules in BEYU that satisfy this department's workflow. */
  modules: string[];
  /** Key capabilities tested. */
  capabilities: string[];
  status: CoverageStatus;
  /** Notes from the coverage test. */
  notes?: string;
}

export const DEPARTMENTS: Department[] = [
  // ═══════════════ Clinical · Ambulatory ═══════════════
  { id: "opd", name: "OPD · Outpatient Clinic", category: "Clinical · Ambulatory", tier: "Tier 1",
    modules: ["EMR", "Appointments", "Prescriptions", "Lab orders", "Billing"], status: "FULL",
    capabilities: ["Queue management", "Consultation note", "Vital capture", "Referral creation"] },
  { id: "family-med", name: "Family Medicine", category: "Clinical · Ambulatory", tier: "Tier 1",
    modules: ["EMR", "Telemedicine", "Prescriptions"], status: "FULL",
    capabilities: ["Continuity of care", "Chronic disease panels", "Wellness visits"] },
  { id: "travel", name: "Travel Medicine", category: "Clinical · Ambulatory", tier: "Tier 3",
    modules: ["EMR", "EPI / Vaccination", "Pharmacy"], status: "FULL",
    capabilities: ["Pre-travel risk assessment", "Yellow card issuance", "Vaccine schedule"] },
  { id: "occupational", name: "Occupational Health", category: "Clinical · Ambulatory", tier: "Tier 3",
    modules: ["EMR", "HR Service", "Reports"], status: "FULL",
    capabilities: ["Pre-employment screen", "Periodic health surveillance", "Work-fitness certs"] },

  // ═══════════════ Clinical · Inpatient ═══════════════
  { id: "ipd-med", name: "IPD · Medical Ward", category: "Clinical · Inpatient", tier: "Tier 2",
    modules: ["EMR", "Bed Management", "Nursing", "Pharmacy"], status: "FULL",
    capabilities: ["Bed allocation", "Round notes", "Medication round", "Discharge summary"] },
  { id: "ipd-surg", name: "IPD · Surgical Ward", category: "Clinical · Inpatient", tier: "Tier 2",
    modules: ["EMR", "Theatre", "Wound care", "Pharmacy"], status: "FULL",
    capabilities: ["Pre/Post-op orders", "Drain charts", "Wound dressing records"] },
  { id: "private-wing", name: "Private Wing / VIP", category: "Clinical · Inpatient", tier: "Tier 3",
    modules: ["EMR", "Bed Management", "Billing"], status: "FULL",
    capabilities: ["Concierge billing", "Private suite mgmt", "Premium service tracking"] },

  // ═══════════════ Clinical · Critical Care ═══════════════
  { id: "icu", name: "ICU · Intensive Care", category: "Clinical · Critical Care", tier: "Tier 3",
    modules: ["EMR", "ICU Dashboard", "Hive Triage AI"], status: "FULL",
    capabilities: ["NEWS scoring", "Vent / Vaso tracking", "Sepsis bundle", "ICU notes"] },
  { id: "hdu", name: "HDU · High Dependency", category: "Clinical · Critical Care", tier: "Tier 3",
    modules: ["EMR", "ICU Dashboard"], status: "FULL",
    capabilities: ["Step-down workflows", "Continuous monitoring"] },
  { id: "nicu", name: "NICU · Neonatal ICU", category: "Clinical · Critical Care", tier: "Tier 4",
    modules: ["Pediatrics", "EMR", "Growth Charts"], status: "FULL",
    capabilities: ["Neonatal vitals", "Phototherapy", "Surfactant tracking"] },
  { id: "picu", name: "PICU · Paediatric ICU", category: "Clinical · Critical Care", tier: "Tier 4",
    modules: ["Pediatrics", "EMR", "ICU Dashboard"], status: "FULL",
    capabilities: ["PEWS scoring", "Weight-based dosing", "Family-centred care"] },
  { id: "stroke", name: "Stroke Unit", category: "Clinical · Critical Care", tier: "Tier 4",
    modules: ["EMR", "Radiology AI", "Clinical Pathway"], status: "FULL",
    capabilities: ["NIHSS scoring", "Thrombolysis pathway", "Door-to-needle KPI"] },
  { id: "burns", name: "Burns Unit", category: "Clinical · Critical Care", tier: "Tier 5",
    modules: ["EMR", "Wound care", "Theatre"], status: "PARTIAL",
    capabilities: ["Lund-Browder chart", "Fluid resuscitation", "Wound dressings"],
    notes: "Lund-Browder body chart UI scheduled v2026.6" },

  // ═══════════════ Clinical · Surgical ═══════════════
  { id: "theatre", name: "Operating Theatres", category: "Clinical · Surgical", tier: "Tier 3",
    modules: ["Theatre", "Surgical Team", "WHO Checklist"], status: "FULL",
    capabilities: ["OR scheduling", "Team assignment", "WHO Surgical Safety Checklist", "Specimen log"] },
  { id: "recovery", name: "Recovery / PACU", category: "Clinical · Surgical", tier: "Tier 3",
    modules: ["EMR", "Anaesthesia"], status: "FULL",
    capabilities: ["Aldrete score", "PACU handover", "Pain scores"] },
  { id: "anaesthesia", name: "Anaesthesia", category: "Clinical · Surgical", tier: "Tier 3",
    modules: ["Theatre", "EMR"], status: "FULL",
    capabilities: ["Anaesthetic plan", "Drug dosing", "Intra-op chart"] },
  { id: "day-surg", name: "Day Surgery", category: "Clinical · Surgical", tier: "Tier 3",
    modules: ["Theatre", "Appointments"], status: "FULL",
    capabilities: ["Same-day workflow", "Discharge criteria"] },
  { id: "trauma", name: "Trauma Centre", category: "Clinical · Surgical", tier: "Tier 4",
    modules: ["Emergency", "Theatre", "Trauma Activation"], status: "FULL",
    capabilities: ["Massive transfusion", "Damage-control surgery", "Trauma scoring"] },

  // ═══════════════ Clinical · Medical Specialty ═══════════════
  { id: "cardio", name: "Cardiology", category: "Clinical · Medical Specialty", tier: "Tier 3",
    modules: ["EMR", "Cardiac Diagnostics", "Theatre (Cath Lab)"], status: "FULL",
    capabilities: ["ECG", "Echo", "Cath Lab report", "Holter"] },
  { id: "neuro", name: "Neurology", category: "Clinical · Medical Specialty", tier: "Tier 4",
    modules: ["EMR", "EEG", "Radiology"], status: "FULL",
    capabilities: ["EEG report", "Seizure log", "MS / Parkinson follow-up"] },
  { id: "gastro", name: "Gastroenterology", category: "Clinical · Medical Specialty", tier: "Tier 3",
    modules: ["EMR", "Endoscopy", "Pathology"], status: "FULL",
    capabilities: ["OGD / Colonoscopy report", "Biopsy tracking"] },
  { id: "hepato", name: "Hepatology", category: "Clinical · Medical Specialty", tier: "Tier 4",
    modules: ["EMR", "Laboratory"], status: "FULL",
    capabilities: ["LFT trends", "Viral hepatitis panels", "Transplant referral"] },
  { id: "nephro", name: "Nephrology + Dialysis", category: "Clinical · Medical Specialty", tier: "Tier 3",
    modules: ["EMR", "Dialysis Unit"], status: "FULL",
    capabilities: ["Dialysis sessions", "Vascular access", "Kt/V tracking"] },
  { id: "pulmo", name: "Pulmonology", category: "Clinical · Medical Specialty", tier: "Tier 3",
    modules: ["EMR", "Pulmonary Function Lab"], status: "FULL",
    capabilities: ["Spirometry", "Bronchoscopy", "Asthma/COPD pathways"] },
  { id: "endo", name: "Endocrinology / Diabetes", category: "Clinical · Medical Specialty", tier: "Tier 3",
    modules: ["EMR", "Diabetes Clinic"], status: "FULL",
    capabilities: ["HbA1c trends", "Insulin titration", "Foot screening"] },
  { id: "rheum", name: "Rheumatology", category: "Clinical · Medical Specialty", tier: "Tier 4",
    modules: ["EMR", "Infusion Centre"], status: "FULL",
    capabilities: ["DAS28 scoring", "Biologic infusions", "Joint injections"] },
  { id: "heme", name: "Haematology", category: "Clinical · Medical Specialty", tier: "Tier 4",
    modules: ["EMR", "Lab · Haem", "Blood Bank"], status: "FULL",
    capabilities: ["Bone marrow reports", "Transfusion mgmt", "Anticoag clinic"] },
  { id: "onco", name: "Oncology · Medical", category: "Clinical · Medical Specialty", tier: "Tier 4",
    modules: ["Oncology", "Chemo Day Unit", "Tumour Board"], status: "FULL",
    capabilities: ["Chemo protocols", "Cycle tracking", "Tumour board MDT"] },
  { id: "radonc", name: "Oncology · Radiation", category: "Clinical · Medical Specialty", tier: "Tier 5",
    modules: ["Oncology", "LINAC Scheduling"], status: "PARTIAL",
    capabilities: ["Treatment planning", "Dose tracking", "Brachytherapy"],
    notes: "Dose-planning DICOM-RT export ships v2026.7" },
  { id: "id", name: "Infectious Diseases / TB / HIV", category: "Clinical · Medical Specialty", tier: "Tier 2",
    modules: ["EMR", "ART Register", "TB Register", "MTUHA"], status: "FULL",
    capabilities: ["ART regimens", "TB DOTS", "Contact tracing", "MTUHA submission"] },
  { id: "derm", name: "Dermatology", category: "Clinical · Medical Specialty", tier: "Tier 3",
    modules: ["EMR", "Image attach", "Pathology"], status: "FULL",
    capabilities: ["Lesion photography", "Biopsy", "Phototherapy"] },
  { id: "geriatrics", name: "Geriatrics", category: "Clinical · Medical Specialty", tier: "Tier 3",
    modules: ["EMR", "Frailty Score", "Polypharmacy AI"], status: "FULL",
    capabilities: ["CGA assessment", "Frailty scoring", "STOPP/START review"] },
  { id: "palliative", name: "Palliative Care", category: "Clinical · Medical Specialty", tier: "Tier 3",
    modules: ["EMR", "Pain Mgmt", "Home Care"], status: "FULL",
    capabilities: ["Symptom scoring", "Advance directives", "Home visits"] },

  // ═══════════════ Clinical · Surgical Specialty ═══════════════
  { id: "ortho", name: "Orthopaedics", category: "Clinical · Surgical Specialty", tier: "Tier 3",
    modules: ["EMR", "Theatre", "Imaging"], status: "FULL",
    capabilities: ["Fracture clinic", "Joint replacement registry", "Plaster room"] },
  { id: "neurosurg", name: "Neurosurgery", category: "Clinical · Surgical Specialty", tier: "Tier 5",
    modules: ["EMR", "Theatre", "Radiology AI"], status: "FULL",
    capabilities: ["Pre-op planning", "ICU recovery", "Neuronavigation"] },
  { id: "cardio-surg", name: "Cardiothoracic Surgery", category: "Clinical · Surgical Specialty", tier: "Tier 5",
    modules: ["EMR", "Theatre", "Perfusion log"], status: "FULL",
    capabilities: ["CABG · valves", "Perfusion records", "Post-op ICU"] },
  { id: "uro", name: "Urology", category: "Clinical · Surgical Specialty", tier: "Tier 3",
    modules: ["EMR", "Theatre", "Endoscopy"], status: "FULL",
    capabilities: ["Cystoscopy", "Stone clinic", "Prostate pathway"] },
  { id: "vascular", name: "Vascular Surgery", category: "Clinical · Surgical Specialty", tier: "Tier 5",
    modules: ["EMR", "Theatre", "Duplex Imaging"], status: "FULL",
    capabilities: ["Duplex reports", "Wound care", "EVAR planning"] },
  { id: "plastic", name: "Plastic & Reconstructive Surgery", category: "Clinical · Surgical Specialty", tier: "Tier 4",
    modules: ["EMR", "Theatre", "Photography"], status: "FULL",
    capabilities: ["Pre-op photos", "Flap monitoring"] },
  { id: "ent", name: "ENT · Otorhinolaryngology", category: "Clinical · Surgical Specialty", tier: "Tier 3",
    modules: ["EMR", "Audiology", "Theatre"], status: "FULL",
    capabilities: ["Audiogram", "Endoscopic exams", "Cochlear implant"] },
  { id: "ophth", name: "Ophthalmology", category: "Clinical · Surgical Specialty", tier: "Tier 3",
    modules: ["EMR", "Optometry Suite", "OCT/Visual Fields"], status: "FULL",
    capabilities: ["OCT", "Visual fields", "Tonometry", "Fundus imaging", "Optical shop"] },
  { id: "dental", name: "Dental & Maxillofacial", category: "Clinical · Surgical Specialty", tier: "Tier 2",
    modules: ["Dental Suite", "Dental AI", "DICOM"], status: "FULL",
    capabilities: ["FDI odontogram", "Caries AI", "Treatment planning", "OPG"] },
  { id: "bariatric", name: "Bariatric Surgery", category: "Clinical · Surgical Specialty", tier: "Tier 5",
    modules: ["EMR", "Theatre", "Dietetics"], status: "FULL",
    capabilities: ["Pre/post-op pathway", "Weight tracking"] },
  { id: "transplant", name: "Transplant Programme", category: "Clinical · Surgical Specialty", tier: "Tier 6",
    modules: ["EMR", "HLA Matching", "Immunosuppression"], status: "PARTIAL",
    capabilities: ["Waitlist", "Match report", "Post-tx follow-up"],
    notes: "HLA matching engine integration scheduled v2027.1" },
  { id: "spine", name: "Spinal Surgery Unit", category: "Clinical · Surgical Specialty", tier: "Tier 5",
    modules: ["EMR", "Theatre", "Rehabilitation"], status: "FULL",
    capabilities: ["Pre-op planning", "Neuro-monitoring", "Rehab pathway"] },

  // ═══════════════ Women & Child Health ═══════════════
  { id: "obs", name: "Obstetrics", category: "Women & Child Health", tier: "Tier 2",
    modules: ["Maternity", "ANC Register", "Partograph"], status: "FULL",
    capabilities: ["ANC visits", "Partograph", "Delivery records", "PNC"] },
  { id: "gynae", name: "Gynaecology", category: "Women & Child Health", tier: "Tier 3",
    modules: ["EMR", "Theatre", "Cytology"], status: "FULL",
    capabilities: ["Cervical screening", "Hysteroscopy", "Family planning"] },
  { id: "maternity", name: "Labour Ward", category: "Women & Child Health", tier: "Tier 2",
    modules: ["Maternity", "Live Partograph"], status: "FULL",
    capabilities: ["Live cervical dilation", "FHR monitoring", "Birth registration"] },
  { id: "fertility", name: "Fertility · IVF", category: "Women & Child Health", tier: "Tier 5",
    modules: ["EMR", "Embryology Log"], status: "PARTIAL",
    capabilities: ["Cycle tracking", "Embryology", "Cryopreservation"],
    notes: "Embryology lab module v2026.8" },
  { id: "peds", name: "Paediatrics", category: "Women & Child Health", tier: "Tier 1",
    modules: ["Pediatrics", "Growth Chart", "EPI"], status: "FULL",
    capabilities: ["WHO growth charts", "EPI schedule", "Weight-based dosing"] },
  { id: "lactation", name: "Lactation Support", category: "Women & Child Health", tier: "Tier 2",
    modules: ["EMR", "Maternity"], status: "FULL",
    capabilities: ["Feeding logs", "Lactation consult notes"] },

  // ═══════════════ Mental Health ═══════════════
  { id: "psych", name: "Psychiatry", category: "Mental Health", tier: "Tier 3",
    modules: ["EMR", "Mental Health Module", "Citizen App self-screen"], status: "FULL",
    capabilities: ["Mental status exam", "Risk assessment", "PHQ-9 / GAD-7"] },
  { id: "psychology", name: "Clinical Psychology", category: "Mental Health", tier: "Tier 3",
    modules: ["EMR", "Telemedicine"], status: "FULL",
    capabilities: ["Therapy sessions", "Treatment plans"] },
  { id: "addiction", name: "Addiction / Substance Use", category: "Mental Health", tier: "Tier 4",
    modules: ["EMR", "Mental Health"], status: "FULL",
    capabilities: ["Detox protocol", "OST register", "Counselling notes"] },

  // ═══════════════ Rehabilitation ═══════════════
  { id: "physio", name: "Physiotherapy", category: "Rehabilitation", tier: "Tier 2",
    modules: ["EMR", "Care Plan", "Appointments"], status: "FULL",
    capabilities: ["Assessment notes", "Exercise prescription", "Outcome scores"] },
  { id: "ot", name: "Occupational Therapy", category: "Rehabilitation", tier: "Tier 3",
    modules: ["EMR", "Care Plan"], status: "FULL",
    capabilities: ["ADL scoring", "Assistive devices"] },
  { id: "speech", name: "Speech & Language Therapy", category: "Rehabilitation", tier: "Tier 3",
    modules: ["EMR", "Telemedicine"], status: "FULL",
    capabilities: ["Swallow assessment", "Speech therapy plans"] },
  { id: "audio", name: "Audiology", category: "Rehabilitation", tier: "Tier 3",
    modules: ["ENT", "Audiogram"], status: "FULL",
    capabilities: ["Audiograms", "Hearing aid fitting"] },
  { id: "pmr", name: "Physical Medicine & Rehabilitation", category: "Rehabilitation", tier: "Tier 4",
    modules: ["EMR", "Rehab Plan"], status: "FULL",
    capabilities: ["FIM scoring", "Multidisciplinary plans"] },
  { id: "cardiac-rehab", name: "Cardiac Rehabilitation", category: "Rehabilitation", tier: "Tier 4",
    modules: ["Cardiology", "Exercise Plan"], status: "FULL",
    capabilities: ["Exercise tolerance", "Risk-factor mgmt"] },

  // ═══════════════ Diagnostics · Imaging ═══════════════
  { id: "xray", name: "X-Ray / Plain Radiography", category: "Diagnostics · Imaging", tier: "Tier 1",
    modules: ["Radiology", "PACS"], status: "FULL",
    capabilities: ["Order entry", "DICOM viewer", "Report sign-out"] },
  { id: "ct", name: "CT Scanner", category: "Diagnostics · Imaging", tier: "Tier 3",
    modules: ["Radiology AI", "PACS"], status: "FULL",
    capabilities: ["AI triage (SDH, PE)", "Dose tracking", "MPR / 3D"] },
  { id: "mri", name: "MRI", category: "Diagnostics · Imaging", tier: "Tier 4",
    modules: ["Radiology", "PACS"], status: "FULL",
    capabilities: ["Sequence planning", "Safety screening"] },
  { id: "us", name: "Ultrasound", category: "Diagnostics · Imaging", tier: "Tier 2",
    modules: ["Radiology", "Point-of-care US"], status: "FULL",
    capabilities: ["Structured reports", "Image capture"] },
  { id: "mammo", name: "Mammography", category: "Diagnostics · Imaging", tier: "Tier 4",
    modules: ["Radiology", "AI BI-RADS"], status: "FULL",
    capabilities: ["BI-RADS reporting", "AI suspicious-lesion flag"] },
  { id: "fluoro", name: "Fluoroscopy", category: "Diagnostics · Imaging", tier: "Tier 3",
    modules: ["Radiology", "PACS"], status: "FULL",
    capabilities: ["Procedure logs", "Contrast tracking"] },
  { id: "nuclear", name: "Nuclear Medicine", category: "Diagnostics · Imaging", tier: "Tier 5",
    modules: ["Radiology", "Radiopharmacy"], status: "PARTIAL",
    capabilities: ["Radioisotope dosing", "SPECT / PET reports"],
    notes: "Radiopharmacy stock module v2026.9" },
  { id: "pet", name: "PET-CT", category: "Diagnostics · Imaging", tier: "Tier 6",
    modules: ["Oncology", "Radiology AI"], status: "PARTIAL",
    capabilities: ["SUV measurement", "Oncology staging"],
    notes: "PET-AI quantification module roadmap 2027.Q1" },

  // ═══════════════ Diagnostics · Laboratory ═══════════════
  { id: "lab-heme", name: "Lab · Haematology", category: "Diagnostics · Laboratory", tier: "Tier 1",
    modules: ["LIS", "Analyzer interface"], status: "FULL",
    capabilities: ["FBC", "Coag", "Reticulocyte", "Sickle screen"] },
  { id: "lab-chem", name: "Lab · Clinical Chemistry", category: "Diagnostics · Laboratory", tier: "Tier 1",
    modules: ["LIS", "Analyzer interface"], status: "FULL",
    capabilities: ["U&E", "LFT", "Lipids", "Cardiac markers"] },
  { id: "lab-micro", name: "Lab · Microbiology", category: "Diagnostics · Laboratory", tier: "Tier 2",
    modules: ["LIS"], status: "FULL",
    capabilities: ["Culture & sensitivity", "TB / HIV testing", "AMR tracking"] },
  { id: "lab-histo", name: "Lab · Histopathology", category: "Diagnostics · Laboratory", tier: "Tier 3",
    modules: ["Pathology"], status: "FULL",
    capabilities: ["Specimen accessioning", "Synoptic reporting", "Cancer staging"] },
  { id: "lab-cyto", name: "Lab · Cytology", category: "Diagnostics · Laboratory", tier: "Tier 3",
    modules: ["Pathology"], status: "FULL",
    capabilities: ["Pap smear", "FNAC", "Liquid-based cytology"] },
  { id: "lab-mol", name: "Lab · Molecular & Genomics", category: "Diagnostics · Laboratory", tier: "Tier 5",
    modules: ["LIS"], status: "FULL",
    capabilities: ["PCR / GeneXpert", "Viral load", "Sequencing pipelines"] },
  { id: "blood-bank", name: "Blood Bank", category: "Diagnostics · Laboratory", tier: "Tier 2",
    modules: ["LIS", "Inventory"], status: "FULL",
    capabilities: ["Group & crossmatch", "Donor registry", "Cold-chain"] },

  // ═══════════════ Diagnostics · Procedural ═══════════════
  { id: "endoscopy", name: "Endoscopy Suite", category: "Diagnostics · Procedural", tier: "Tier 3",
    modules: ["EMR", "Theatre", "Imaging"], status: "FULL",
    capabilities: ["OGD / Colonoscopy", "Biopsy logs", "Decontamination tracking"] },
  { id: "cath-lab", name: "Cardiac Cath Lab", category: "Diagnostics · Procedural", tier: "Tier 4",
    modules: ["Cardiology", "Theatre"], status: "FULL",
    capabilities: ["PCI procedure log", "Stent registry"] },
  { id: "ekg", name: "ECG / Cardiac Diagnostics", category: "Diagnostics · Procedural", tier: "Tier 1",
    modules: ["Cardiac Diagnostics"], status: "FULL",
    capabilities: ["12-lead ECG", "Holter", "Stress test"] },
  { id: "eeg", name: "EEG / Neurophysiology", category: "Diagnostics · Procedural", tier: "Tier 3",
    modules: ["Neurology"], status: "FULL",
    capabilities: ["EEG capture", "EMG / NCS"] },
  { id: "pft", name: "Pulmonary Function Lab", category: "Diagnostics · Procedural", tier: "Tier 3",
    modules: ["Pulmonology"], status: "FULL",
    capabilities: ["Spirometry", "DLCO", "Body plethysmography"] },
  { id: "sleep", name: "Sleep Lab", category: "Diagnostics · Procedural", tier: "Tier 4",
    modules: ["EMR"], status: "PARTIAL",
    capabilities: ["Polysomnography review", "CPAP titration"],
    notes: "PSG signal viewer scheduled 2026.10" },
  { id: "ent-diag", name: "Audiometry / ENT Diagnostics", category: "Diagnostics · Procedural", tier: "Tier 3",
    modules: ["ENT"], status: "FULL",
    capabilities: ["Pure-tone audiometry", "Tympanometry"] },

  // ═══════════════ Treatment Services ═══════════════
  { id: "pharm", name: "Pharmacy (Inpatient + Outpatient)", category: "Treatment Services", tier: "Tier 1",
    modules: ["Pharmacy", "Pharmacy AI", "Controlled-substance log"], status: "FULL",
    capabilities: ["Dispensing", "Interactions", "Witnessed controlled dispense", "Cold chain"] },
  { id: "infusion", name: "IV Therapy / Infusion Centre", category: "Treatment Services", tier: "Tier 3",
    modules: ["EMR", "Day Care"], status: "FULL",
    capabilities: ["Chair scheduling", "Infusion checklist"] },
  { id: "chemo", name: "Chemotherapy Day Unit", category: "Treatment Services", tier: "Tier 4",
    modules: ["Oncology"], status: "FULL",
    capabilities: ["Regimen builder", "Cycle prep", "Vital monitoring"] },
  { id: "radio-tx", name: "Radiotherapy (LINAC + Brachy)", category: "Treatment Services", tier: "Tier 5",
    modules: ["Oncology"], status: "PARTIAL",
    capabilities: ["Treatment fractions", "Image-guided RT"],
    notes: "DICOM-RT planning import in 2026.7" },
  { id: "dialysis", name: "Renal Dialysis", category: "Treatment Services", tier: "Tier 3",
    modules: ["Nephrology"], status: "FULL",
    capabilities: ["HD session", "PD recording", "Vascular access"] },
  { id: "wound", name: "Wound Care Clinic", category: "Treatment Services", tier: "Tier 2",
    modules: ["EMR", "Image attach"], status: "FULL",
    capabilities: ["Wound photography", "Dressings", "Healing trends"] },
  { id: "hbot", name: "Hyperbaric Oxygen", category: "Treatment Services", tier: "Tier 6",
    modules: ["EMR"], status: "ROADMAP",
    capabilities: ["Chamber session log", "Indication tracking"],
    notes: "Specialty module — to be built on tenant request" },

  // ═══════════════ Support Clinical ═══════════════
  { id: "nutrition", name: "Nutrition & Dietetics", category: "Support Clinical", tier: "Tier 2",
    modules: ["EMR", "Care Plan"], status: "FULL",
    capabilities: ["Diet plan", "Malnutrition screen", "TPN tracking"] },
  { id: "social-work", name: "Medical Social Work", category: "Support Clinical", tier: "Tier 2",
    modules: ["EMR", "Patient Portal"], status: "FULL",
    capabilities: ["Welfare assessment", "Discharge planning"] },
  { id: "chaplain", name: "Pastoral Care / Chaplaincy", category: "Support Clinical", tier: "Tier 3",
    modules: ["EMR"], status: "FULL",
    capabilities: ["Spiritual care notes", "End-of-life support"] },
  { id: "him", name: "HIM · Medical Records", category: "Support Clinical", tier: "Tier 1",
    modules: ["EMR", "Audit", "Coding AI"], status: "FULL",
    capabilities: ["Chart audit", "ICD-11 coding", "Release of information"] },
  { id: "genetics", name: "Genetic Counselling", category: "Support Clinical", tier: "Tier 5",
    modules: ["EMR", "Molecular Lab"], status: "FULL",
    capabilities: ["Pedigree tracking", "Carrier screening"] },

  // ═══════════════ Administration ═══════════════
  { id: "admin", name: "Hospital Administration", category: "Administration", tier: "Tier 1",
    modules: ["Admin Console", "Tenant Mgmt"], status: "FULL",
    capabilities: ["Multi-site config", "Roles", "Tenant isolation"] },
  { id: "hr", name: "Human Resources", category: "Administration", tier: "Tier 1",
    modules: ["HR Service", "Payroll", "Biometric Attendance"], status: "FULL",
    capabilities: ["Registry", "Credentials", "Payroll", "Shifts", "ESS"] },
  { id: "finance-admin", name: "Finance & Accounting", category: "Administration", tier: "Tier 1",
    modules: ["Finance", "GL"], status: "FULL",
    capabilities: ["AR / AP", "GL", "Trial balance"] },
  { id: "billing-admin", name: "Billing & Cashier", category: "Administration", tier: "Tier 1",
    modules: ["Billing", "RCM"], status: "FULL",
    capabilities: ["Invoicing", "Cashier", "Receipts", "M-Pesa"] },
  { id: "insurance-admin", name: "Insurance & Claims", category: "Administration", tier: "Tier 1",
    modules: ["Claims", "NHIF Integration"], status: "FULL",
    capabilities: ["Eligibility", "Pre-auth", "Submission", "Denial mgmt"] },
  { id: "procurement", name: "Procurement & Stores", category: "Administration", tier: "Tier 1",
    modules: ["Procurement", "Inventory"], status: "FULL",
    capabilities: ["Suppliers", "RFQ", "PO", "GRN", "3-way match"] },
  { id: "biomed", name: "Biomedical Engineering", category: "Administration", tier: "Tier 2",
    modules: ["Asset Mgmt"], status: "FULL",
    capabilities: ["Equipment registry", "PPM schedule", "Calibration"] },
  { id: "qa", name: "Quality & Compliance", category: "Administration", tier: "Tier 1",
    modules: ["Governance", "Audit", "MTUHA"], status: "FULL",
    capabilities: ["KPI dashboards", "Incident reports", "Compliance score"] },
  { id: "ipc", name: "Infection Prevention & Control", category: "Administration", tier: "Tier 1",
    modules: ["IPC Surveillance", "Lab Microbiology"], status: "FULL",
    capabilities: ["HAI surveillance", "Hand hygiene audits"] },
  { id: "risk", name: "Risk Management", category: "Administration", tier: "Tier 2",
    modules: ["Governance", "Audit", "Board"], status: "FULL",
    capabilities: ["Risk register", "Incident review", "Clinical governance"] },
  { id: "legal", name: "Legal & Compliance", category: "Administration", tier: "Tier 2",
    modules: ["Vault", "Smart Contracts"], status: "FULL",
    capabilities: ["Contracts vault", "Compliance calendar", "DPO"] },
  { id: "it", name: "IT & Health Informatics", category: "Administration", tier: "Tier 1",
    modules: ["Security Ops", "Tenant Admin"], status: "FULL",
    capabilities: ["RBAC mgmt", "Key rotation", "Integration mgmt"] },
  { id: "marketing", name: "Marketing & Patient Relations", category: "Administration", tier: "Tier 2",
    modules: ["Citizen App", "CRM"], status: "FULL",
    capabilities: ["Campaign mgmt", "Patient feedback", "NPS"] },

  // ═══════════════ Facilities & Support ═══════════════
  { id: "er", name: "Emergency Department", category: "Specialized Units", tier: "Tier 2",
    modules: ["Emergency", "Triage AI", "Ambulance"], status: "FULL",
    capabilities: ["ESI triage", "Trauma activation", "Ambulance dispatch"] },
  { id: "ambulance", name: "Ambulance Service", category: "Specialized Units", tier: "Tier 2",
    modules: ["Emergency", "GPS Dispatch"], status: "FULL",
    capabilities: ["Fleet status", "Dispatch", "Pre-hospital notes"] },
  { id: "house", name: "Housekeeping / Linen", category: "Facilities & Support", tier: "Tier 1",
    modules: ["Operations Console"], status: "FULL",
    capabilities: ["Cleaning roster", "Bed turnover"] },
  { id: "cssd", name: "CSSD · Sterilisation", category: "Facilities & Support", tier: "Tier 2",
    modules: ["Inventory", "Theatre"], status: "FULL",
    capabilities: ["Sterilisation cycles", "Instrument tracking"] },
  { id: "catering", name: "Catering / Food Services", category: "Facilities & Support", tier: "Tier 2",
    modules: ["Operations Console", "Nutrition"], status: "FULL",
    capabilities: ["Diet orders", "Tray tracking"] },
  { id: "maint", name: "Facilities Maintenance", category: "Facilities & Support", tier: "Tier 1",
    modules: ["Asset Mgmt"], status: "FULL",
    capabilities: ["Work orders", "Preventive maintenance"] },
  { id: "security", name: "Security & Access Control", category: "Facilities & Support", tier: "Tier 1",
    modules: ["Security Ops"], status: "FULL",
    capabilities: ["Access control", "Visitor management", "CCTV integration"] },
  { id: "morgue", name: "Mortuary", category: "Facilities & Support", tier: "Tier 2",
    modules: ["EMR"], status: "FULL",
    capabilities: ["Body register", "Release authorisation"] },
  { id: "transport", name: "Patient Transport", category: "Facilities & Support", tier: "Tier 2",
    modules: ["Operations Console"], status: "FULL",
    capabilities: ["Inter-ward transfers", "Wheelchair / trolley pool"] },
];

// Department category metadata
export const CATEGORIES: { id: Category; color: string; icon: string }[] = [
  { id: "Clinical · Ambulatory", color: "#1E3A8A", icon: "heart" },
  { id: "Clinical · Inpatient", color: "#0B1D3A", icon: "building" },
  { id: "Clinical · Critical Care", color: "#dc2626", icon: "warning" },
  { id: "Clinical · Surgical", color: "#7c3aed", icon: "scan" },
  { id: "Clinical · Medical Specialty", color: "#0d9488", icon: "heart" },
  { id: "Clinical · Surgical Specialty", color: "#6366f1", icon: "scan" },
  { id: "Women & Child Health", color: "#be123c", icon: "users" },
  { id: "Mental Health", color: "#8b5cf6", icon: "brain" },
  { id: "Rehabilitation", color: "#0891b2", icon: "heart" },
  { id: "Diagnostics · Imaging", color: "#7c3aed", icon: "monitor" },
  { id: "Diagnostics · Laboratory", color: "#0d9488", icon: "lab" },
  { id: "Diagnostics · Procedural", color: "#b45309", icon: "scan" },
  { id: "Treatment Services", color: "#557345", icon: "pill" },
  { id: "Support Clinical", color: "#475569", icon: "users" },
  { id: "Administration", color: "#D4AF37", icon: "settings" },
  { id: "Facilities & Support", color: "#64748b", icon: "building" },
  { id: "Specialized Units", color: "#dc2626", icon: "zap" },
];

export function coverageStats() {
  const total = DEPARTMENTS.length;
  const full = DEPARTMENTS.filter(d => d.status === "FULL").length;
  const partial = DEPARTMENTS.filter(d => d.status === "PARTIAL").length;
  const roadmap = DEPARTMENTS.filter(d => d.status === "ROADMAP").length;
  return {
    total,
    full,
    partial,
    roadmap,
    pct: Math.round(((full + partial * 0.5) / total) * 100),
    fullPct: Math.round((full / total) * 100),
  };
}

export function byCategory(c: Category) { return DEPARTMENTS.filter(d => d.category === c); }
