import { predecessorInitialHistory } from "../helpers/predecessor-initial-history";
import { expect, it } from "vitest";
import { Client } from "pg";
import { randomUUID } from "node:crypto";
import { mkdtempSync, mkdirSync, copyFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
const adminUrl=process.env.BEYU_ADMIN_DATABASE_URL;
it.skipIf(!adminUrl)("0057 preserves original membership and decision history and never revives ended seats on reseed",async()=>{
 const root=process.cwd(),name=`beyu_membership_upgrade_${randomUUID().replaceAll("-","")}`;
 const master=new Client({connectionString:adminUrl});await master.connect();
 const admin=new URL(adminUrl!);admin.pathname=`/${name}`;
 const runtime=new URL(process.env.BEYU_RUNTIME_DATABASE_URL!);runtime.pathname=`/${name}`;
 const env={...process.env,BEYU_ADMIN_DATABASE_URL:admin.href,BEYU_TEST_DATABASE_URL:admin.href,DATABASE_URL:runtime.href,BEYU_RUNTIME_DATABASE_URL:runtime.href};
 mkdirSync(join(root,"tmp/governance"),{recursive:true});const dir=mkdtempSync(join(root,"tmp/governance/membership-upgrade-"));mkdirSync(join(dir,"drizzle"));
 for(const f of readdirSync(join(root,"drizzle")).filter(f=>/^\d+.*\.sql$/.test(f)&&Number(f.slice(0,4))<=56))copyFileSync(join(root,"drizzle",f),join(dir,"drizzle",f));
 const run=(script:string,cwd:string,label:string)=>{const r=spawnSync(process.execPath,[join(root,"node_modules/tsx/dist/cli.mjs"),script],{cwd,env,encoding:"utf8",timeout:90000});writeFileSync(join(dir,`${label}.log`),(r.stdout??"")+(r.stderr??""));expect(r.status,`see ${join(dir,`${label}.log`)}`).toBe(0);};
 const client=new Client({connectionString:admin.href});let created=false;
 try{
  await master.query(`create database ${name} owner postgres`);created=true;
  run(join(root,"scripts/migrate.ts"),dir,"predecessor");run(join(root,"scripts/setup-db-role.ts"),root,"runtime-before");run(join(root,"src/db/seed.ts"),root,"seed");
  await client.connect();
  await predecessorInitialHistory(client);
  const tables=["governance_bodies","governance_body_establishments","governance_charters","governance_charter_terms","governance_appointments","governance_members","resolutions","resolution_votes","role_assignments","governance_capability_registry","audit_log","enterprise_events"];
  const snapshot=async()=>{const result:Record<string,unknown>={};for(const t of tables)result[t]=(await client.query(`select * from ${t} t order by to_jsonb(t)::text`)).rows;return result;};
  const before=await snapshot();
  expect((await client.query("select status from governance_appointments")).rows).toEqual(Array.from({length:4},()=>({status:"ACCEPTED"})));
  copyFileSync(join(root,"drizzle/0057_governance_membership_lifecycle.sql"),join(dir,"drizzle/0057_governance_membership_lifecycle.sql"));
  run(join(root,"scripts/migrate.ts"),dir,"upgrade");run(join(root,"scripts/migrate.ts"),dir,"noop");run(join(root,"scripts/setup-db-role.ts"),root,"runtime-after");
    const after=await snapshot();
  const members=after.governance_members as Record<string,unknown>[];
  after.governance_members=members.map(({lifecycle_status,lifecycle_revision,...original})=>{expect(lifecycle_status).toBe("ACTIVE");expect(lifecycle_revision).toBe(0);return original;});
  expect(after).toEqual(before);
  expect((await client.query("select id from governance_membership_changes")).rowCount).toBe(0);
  expect(Number((await client.query("select count(*) as n from beyu_migrations where mode='APPLIED'")).rows[0].n)).toBe(58);
  await client.query("begin");await client.query("set local role beyu_runtime");
  expect((await client.query("select rolsuper,rolbypassrls from pg_roles where rolname=current_user")).rows[0]).toEqual({rolsuper:false,rolbypassrls:false});
  expect((await client.query("select id from governance_membership_changes")).rowCount).toBe(0);
  await client.query("rollback");
  const m=(await client.query("select * from governance_members where body_id='GOV_GROUP_BOARD' and seat_role='CHAIR'")).rows[0];
  const tenant=(await client.query("select tenant_id from governance_bodies where id=$1",[m.body_id])).rows[0].tenant_id;
  await client.query("begin");await client.query("set local role beyu_runtime");
  await client.query("select set_config('beyu.current_tenant_ids',$1,true),set_config('beyu.governance_context','on',true),set_config('beyu.governance_actions_read','on',true),set_config('beyu.governance_entity_ids','',true),set_config('beyu.governance_classifications','PUBLIC,INTERNAL,CONFIDENTIAL,RESTRICTED,HIGHLY_RESTRICTED',true),set_config('beyu.membership_actor','USR_AMANI_BEYU',true),set_config('beyu.membership_change_id','GMC_UPGRADE',true)",[tenant]);
  await client.query(`insert into governance_membership_changes(id,body_id,member_id,authority_body_id,command,from_status,to_status,member_revision,status,document_id,document_version,document_checksum,classification,rationale,proposed_by_user_id,proposed_by_party_id,applied_by_user_id,applied_at)
  select 'GMC_UPGRADE',$1,$2,$1,'RESIGN','ACTIVE','RESIGNED',0,'APPLIED',id,version,checksum,classification,'Voluntary resignation after upgrade','USR_AMANI_BEYU',$3,'USR_AMANI_BEYU',now() from documents where id='DOC_D4'`,[m.body_id,m.id,m.party_id]);
  await client.query("update governance_members set lifecycle_status='RESIGNED',lifecycle_revision=1 where id=$1",[m.id]);await client.query("commit");
  run(join(root,"src/db/seed.ts"),root,"reseed-does-not-revive");
  expect((await client.query("select lifecycle_status,lifecycle_revision,appointed_on,retired_on from governance_members where id=$1",[m.id])).rows).toEqual([{lifecycle_status:"RESIGNED",lifecycle_revision:1,appointed_on:m.appointed_on,retired_on:m.retired_on}]);
 }finally{await client.end();if(created)await master.query(`drop database ${name} with (force)`);await master.end();}
},180000);
