/**
 * Machine-readable Ujenzi capability registry.
 * Statuses are honest: IMPLEMENTED | PARTIAL | PLANNED | NOT_CONNECTED | NOT_CERTIFIED | DATA_REQUIRED | BLOCKED.
 */
export type UjenziCapabilityStatus =
  | "IMPLEMENTED"
  | "PARTIAL"
  | "PLANNED"
  | "NOT_CONNECTED"
  | "NOT_CERTIFIED"
  | "DATA_REQUIRED"
  | "BLOCKED";

export type UjenziCapability = {
  capability: string;
  status: UjenziCapabilityStatus;
  owner: string;
  tables: string[];
  api: string[];
  events: string[];
  noeliaTools: string[];
  notes: string;
};

export const UJENZI_CAPABILITY_REGISTRY: UjenziCapability[] = [
  {
    capability: "projects",
    status: "IMPLEMENTED",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_projects", "ujenzi_briefs", "ujenzi_cost_trackers"],
    api: ["/api/v1/ujenzi/projects", "/api/v1/ujenzi/dashboard"],
    events: ["PROJECT_CREATED"],
    noeliaTools: ["ujenzi.operations.observe", "ujenzi.project.observe"],
    notes: "Lifecycle anchor. Cost tracker is not a ledger.",
  },
  {
    capability: "land_sites",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_land_sites"],
    api: ["/api/v1/ujenzi/sites"],
    events: ["SITE_REGISTERED"],
    noeliaTools: ["ujenzi.digital_twin.query"],
    notes: "CRS required. Geometry source USER_ENTERED until survey import.",
  },
  {
    capability: "survey_observations",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_survey_observations"],
    api: ["/api/v1/ujenzi/surveys"],
    events: [],
    noeliaTools: [],
    notes: "Coordinates optional; missing → DATA_REQUIRED. Unknown CRS refused.",
  },
  {
    capability: "gis_ingest",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_gis_datasets"],
    api: ["/api/v1/ujenzi/gis"],
    events: [],
    noeliaTools: [],
    notes: "GeoJSON FeatureCollection only. No WMS/WFS. Renderer NOT_IMPLEMENTED.",
  },
  {
    capability: "defects_rfis_schedule",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_defects", "ujenzi_rfis", "ujenzi_schedule_activities"],
    api: ["/api/v1/ujenzi/defects", "/api/v1/ujenzi/rfis", "/api/v1/ujenzi/schedule"],
    events: [],
    noeliaTools: [],
    notes: "Operational records. Not a P6/Primavera clone.",
  },
  {
    capability: "soil",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_soil_tests"],
    api: ["/api/v1/ujenzi/soil"],
    events: [],
    noeliaTools: ["ujenzi.operations.observe"],
    notes: "Missing parameters → DATA_REQUIRED. Never fabricated.",
  },
  {
    capability: "engineering_calculations",
    status: "NOT_CERTIFIED",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_engineering_calculations", "ujenzi_engineering_standards"],
    api: ["/api/v1/ujenzi/calculations"],
    events: ["CALCULATION_CREATED"],
    noeliaTools: ["ujenzi.operations.observe"],
    notes: "Decision support only. Noelia cannot certify.",
  },
  {
    capability: "digital_twin",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: [
      "ujenzi_buildings",
      "ujenzi_levels",
      "ujenzi_spaces",
      "ujenzi_elements",
      "ujenzi_systems",
      "ujenzi_assets",
      "ujenzi_twin_edges",
    ],
    api: ["/api/v1/ujenzi/digital-twin"],
    events: [],
    noeliaTools: ["ujenzi.digital_twin.query"],
    notes: "Identifier graph. Not a 3D viewer.",
  },
  {
    capability: "bim",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_bim_models", "ujenzi_model_objects", "ujenzi_bim_artifacts"],
    api: ["/api/v1/ujenzi/bim"],
    events: [],
    noeliaTools: [],
    notes: "SHA-256 artifact register + IFC STEP sniff. geometryParsed false. Viewer NOT_IMPLEMENTED.",
  },
  {
    capability: "quality_ncr",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_quality_ncrs"],
    api: ["/api/v1/ujenzi/quality"],
    events: [],
    noeliaTools: [],
    notes: "NCR records with optional twin object link. Not a full ITP suite.",
  },
  {
    capability: "procurement_rfq",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_rfqs", "ujenzi_quotations"],
    api: ["/api/v1/ujenzi/rfq"],
    events: [],
    noeliaTools: [],
    notes: "RFQ/quote records. Autonomous award refused. journalsPosted always false.",
  },
  {
    capability: "asset_work_orders",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_work_orders", "ujenzi_assets"],
    api: ["/api/v1/ujenzi/work-orders"],
    events: [],
    noeliaTools: [],
    notes: "Work orders do not post Finance journals.",
  },
  {
    capability: "reality_capture",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_reality_captures"],
    api: ["/api/v1/ujenzi/reality"],
    events: [],
    noeliaTools: [],
    notes: "Checksum register only. Computer vision NOT_IMPLEMENTED. BIM vs reality BLOCKED.",
  },
  {
    capability: "design_intelligence",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_design_alternatives"],
    api: ["/api/v1/ujenzi/design-alternatives"],
    events: [],
    noeliaTools: [],
    notes: "Ranks only user-supplied scores. Human approval required.",
  },
  {
    capability: "compliance_rules",
    status: "PARTIAL",
    owner: "CHIEF_RISK_COMPLIANCE",
    tables: ["ujenzi_compliance_requirements", "ujenzi_compliance_evaluations"],
    api: ["/api/v1/ujenzi/compliance"],
    events: [],
    noeliaTools: [],
    notes: "User-cited rules only. Official government status NOT_CONNECTED.",
  },
  {
    capability: "construction_execution",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: [
      "ujenzi_work_packages",
      "ujenzi_work_package_deps",
      "ujenzi_site_reports",
      "ujenzi_submittals",
      "ujenzi_material_movements",
    ],
    api: ["/api/v1/ujenzi/work-packages", "/api/v1/ujenzi/site-reports"],
    events: [],
    noeliaTools: [],
    notes: "Work packages, planned vs actual qty, site diaries, submittals, material movements. Not a P6 clone.",
  },
  {
    capability: "quality_itp",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_itps", "ujenzi_itp_results"],
    api: ["/api/v1/ujenzi/itp"],
    events: [],
    noeliaTools: [],
    notes: "ITP + results remain NOT_CERTIFIED.",
  },
  {
    capability: "sustainability_metrics",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_sustainability_metrics"],
    api: ["/api/v1/ujenzi/sustainability"],
    events: [],
    noeliaTools: [],
    notes: "User-supplied methodology and source required. No fabricated carbon factors.",
  },
  {
    capability: "handover_readiness",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_commissioning_tests", "ujenzi_quality_ncrs", "ujenzi_assets"],
    api: [],
    events: [],
    noeliaTools: ["ujenzi.handover.check"],
    notes: "Handover blocked on open NCRs/uncertified commissioning. Asset only from APPROVED tests. Noelia observes only.",
  },
  {
    capability: "4d_5d_links",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_work_packages", "ujenzi_boq_items", "ujenzi_twin_edges"],
    api: [],
    events: [],
    noeliaTools: [],
    notes: "WP↔BOQ unit-checked links. Viewer NOT_IMPLEMENTED. Earned value PARTIAL. CAP_POSTING LOCKED.",
  },
  {
    capability: "gis_geobim",
    status: "PARTIAL",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_land_sites", "ujenzi_gis_datasets", "ujenzi_gis_features"],
    api: ["/api/v1/ujenzi/gis"],
    events: [],
    noeliaTools: [],
    notes: "GeoJSON FeatureCollection ingest + feature rows. WMS/WFS/GeoTIFF NOT_IMPLEMENTED. Renderer NOT_IMPLEMENTED.",
  },
  {
    capability: "government_integration",
    status: "NOT_CONNECTED",
    owner: "CHIEF_RISK_COMPLIANCE",
    tables: ["ujenzi_government_applications"],
    api: [],
    events: [],
    noeliaTools: ["government.integration.status"],
    notes: "Uses BEYU Government Integration Fabric. Official APIs not live.",
  },
  {
    capability: "finance_handoff",
    status: "BLOCKED",
    owner: "GROUP_CFO",
    tables: ["ujenzi_cost_trackers", "ujenzi_progress_certificates"],
    api: ["/api/v1/ujenzi/progress"],
    events: [],
    noeliaTools: [],
    notes: "CAP_POSTING LOCKED. JournalsPosted always false from Ujenzi.",
  },
  {
    capability: "offline_sync",
    status: "IMPLEMENTED",
    owner: "SECTOR_OPERATOR",
    tables: ["ujenzi_sync_envelopes"],
    api: ["/api/v1/ujenzi/sync"],
    events: [],
    noeliaTools: [],
    notes: "Idempotent envelopes. Server authorization still required.",
  },
];
